#!/usr/bin/env python3
"""Generate STATUS.md entirely from the data. Nothing in it is hand-typed.

WHY GENERATED
  The hand-maintained STATUS.md drifted three separate times. Worse, it opened
  with "All four submission parts are complete" while reporting 251 oligos /
  1,786 measurements / 47 sources against actual values of 259 / 1,959 / 70, and
  it labelled a row count ("human_clinical 852") with the words "human trials".
  A document that cannot drift is the only durable fix.

  It also separates four things the old file ran together, as Beebop's Priority 5
  requires: whether a DOCUMENT EXISTS, whether its content is SOURCE-VERIFIED,
  whether it is SCIENTIST-APPROVED, and whether it is RELEASE-ELIGIBLE. A
  generated PDF is not an approved dataset.

Usage:  python3 scripts/build_status.py
"""
import csv, json, os, collections

ENDPOINT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ENDPOINT, "data")
SCI = os.path.join(ENDPOINT, "curation", "scientist_v09")


def rd(p):
    if not os.path.exists(p): return []
    with open(p, newline="", encoding="utf-8") as f: return list(csv.DictReader(f))


def main():
    oligos = rd(os.path.join(DATA, "oligos.csv"))
    meas = rd(os.path.join(DATA, "measurements.csv"))
    studies = rd(os.path.join(DATA, "studies.csv"))
    xwalk = rd(os.path.join(SCI, "crosswalk.csv"))
    conflicts = rd(os.path.join(SCI, "conflicts.csv"))
    recoveries = rd(os.path.join(SCI, "recoveries.csv"))

    sc = collections.Counter(m["subject_class"] for m in meas)
    hc = sc.get("human_clinical", 0)
    hl = sc.get("human_in_vitro", 0) + sc.get("human_ex_vivo", 0)
    an = sum(v for k, v in sc.items() if k.startswith("animal"))
    ur = sc.get("unspecified", 0) + sc.get("multi_species", 0)
    nsrc = len({(m["source_id"], m["source_ref"]) for m in meas})
    legacy = len({m["source_id"] for m in meas})
    g = collections.Counter(m["thrombocytopenia_grade"] for m in meas)

    nseq = sum(1 for o in oligos if o["sequence_5to3"] not in ("", "TBD", "NA", "NOT_REPORTED"))
    nmap = sum(1 for o in oligos if o["modification_map"] not in ("", "TBD"))
    npur = sum(1 for o in oligos if o["purity_pct"] not in ("", "TBD"))
    elig = [o for o in oligos if o.get("clinical_model_eligibility") not in ("NO", "")]
    mech = [o for o in oligos if o.get("mechanistic_model_eligibility") == "YES"]
    adj = sum(1 for o in oligos if (o.get("scientist_record_id") or "").strip())
    grp = collections.Counter(o.get("exact_sequence_group", "") for o in oligos)
    shared = {k: v for k, v in grp.items() if v > 1 and k}

    approved = {}
    ap = os.path.join(DATA, "approved_analyses.json")
    if os.path.exists(ap): approved = json.load(open(ap))

    ladder = rd(os.path.join(DATA, "study_counts.csv"))
    if studies and ladder:
        L = {r["measure"]: r for r in ladder}
        def n(k, default="?"):
            r = L.get(k)
            return r["n"] if r else default
        defensible = n("... and not intended pharmacology")
        trial_line = (f"**{defensible}** trials carry a defensible platelet-toxicity claim: "
                      f"endpoint demonstrably assessed, measurement rows present, and a platelet "
                      f"change is not the intended effect")
        trial_state = ("ESTABLISHED AS A LADDER, NOT A SINGLE NUMBER — see `data/study_counts.csv`. "
                       "A single headline figure is not defensible here: of the "
                       f"{n('... typed as a trial')} units typed as a trial, "
                       f"{n('... carrying at least one measurement row')} carry any measurement "
                       "row at all; the rest are trial-grain ANCHORS, identified so that pooled "
                       "data can be attributed, not trials this dataset holds data for.")
    else:
        trial_line = "**not yet established**"
        trial_state = ("NOT ESTABLISHED. The study registry is still being built. Until it "
                       "exists this dataset reports OUTCOME RECORDS only and must not publish "
                       "a trial count.")

    L = []
    w = L.append
    w("# Status — OligoTox-Thrombocytopenia\n")
    w("> **This file is generated by `scripts/build_status.py`. Do not edit it by hand.**")
    w("> Every number below is computed from the data in this folder at build time.\n")
    w("Scope: **thrombocytopenia only**. Nothing here speaks for any other endpoint.\n")
    w("---\n")

    w("## 1. Four status axes, kept separate\n")
    w("A generated document is not a verified dataset, and a verified dataset is not an")
    w("approved one. Conflating these is how a project talks itself into believing it is")
    w("finished. The four axes:\n")
    w("| Axis | State |")
    w("|---|---|")
    w("| **Documents generated** | narrative, methodology, PADP, sources PDFs build from templates; "
      "counts are injected, never typed |")
    w(f"| **Source verification** | partial — {len(meas)} measurement rows, a verified subset only; "
      "see the verification warnings in `qc_thrombo.py` output |")
    w(f"| **Scientist approval** | NOT COMPLETE — {len(elig)} of {len(oligos)} compounds carry any "
      "clinical model eligibility, **every one PROVISIONAL**; the scientist package records "
      "0 qualified clinical negatives |")
    w("| **Release eligibility** | **NOT ELIGIBLE** — the scientist package gate SRQ-TMB-012 "
      "requires scientific review before any public freeze |")
    w("")

    w("## 2. Human clinical trials\n")
    w(f"Verified unique human clinical trials: {trial_line}.\n")
    w(f"**Status: {trial_state}**\n")
    if studies and ladder:
        w("| Count | n | Definition |")
        w("|---|---:|---|")
        for r in ladder:
            w(f"| {r['measure']} | {r['n'] if r['n'] != '0' else '—'} | {r['definition']} |")
        w("")
        nest = rd(os.path.join(DATA, "study_nesting_ledger.csv"))
        w(f"`data/study_nesting_ledger.csv` declares **{len(nest)} overlaps** where a trial recorded "
          "here individually is also inside a pooled analysis recorded here. Each edge was "
          "established by arithmetic agreement on arm sizes, never by compound-name similarity. "
          "**Never sum a pooled analysis with its member trials.**\n")
    w("The distinction that matters: a trial is not a row. The table below counts rows.\n")
    w("| Evidence class | Outcome records | Compounds |")
    w("|---|---:|---:|")
    w(f"| human clinical | {hc} | {len({m['oligo_id'] for m in meas if m['subject_class']=='human_clinical'})} |")
    w(f"| human laboratory / ex vivo | {hl} | {len({m['oligo_id'] for m in meas if m['subject_class'] in ('human_in_vitro','human_ex_vivo')})} |")
    w(f"| **human total** | **{hc+hl}** | |")
    w(f"| animal (appendix) | {an} | {len({m['oligo_id'] for m in meas if m['subject_class'].startswith('animal')})} |")
    w(f"| unresolved | {ur} | assigned to neither side |")
    w(f"| **all records** | **{len(meas)}** | **{len(oligos)}** |")
    w("")
    w(f"Grade distribution 0/1/2/3: {g.get('0',0)} / {g.get('1',0)} / {g.get('2',0)} / {g.get('3',0)}\n")
    w(f"Distinct source documents: **{nsrc}** (from {legacy} legacy `source_id` values — "
      f"`source_id` is NOT unique per document, so `source_uid` in "
      f"`data/sources_inventory.csv` is the stable key).\n")

    w("## 3. Scientist governance (package v0.9)\n")
    st = collections.Counter(x["crosswalk_status"] for x in xwalk)
    w(f"Reconciled against `GOG_OligoTox_Thrombo_Integrated_Phase2_v0.9.xlsx` "
      f"({len(xwalk)} scientist sequence records).\n")
    w("| Crosswalk outcome | n |")
    w("|---|---:|")
    for k, v in st.most_common(): w(f"| {k} | {v} |")
    w(f"| conflicts outstanding | {len(conflicts)} |")
    w(f"| values recovered from the scientist package | {len(recoveries)} |")
    w("")
    w(f"- Compounds carrying a scientist disposition: **{adj} / {len(oligos)}**. "
      f"The remaining {len(oligos)-adj} are `NOT_ADJUDICATED` and therefore model-ineligible by default.")
    w(f"- Clinical model eligibility: **{len(elig)}** compounds, all PROVISIONAL "
      f"({', '.join(sorted(o['oligo_name'] for o in elig))}).")
    w(f"- Mechanistic model eligibility: **{len(mech)}** compounds.")
    w("- Qualified clinical negatives: **0**. The scientist package rules "
      "`CLEAN_CLINICAL_NEGATIVE` *NOT YET AVAILABLE* and all 21 audited candidates ineligible. "
      "Absence of a reported platelet event is never encoded as a negative.")
    w(f"- Leakage grouping: **{len(shared)} exact-sequence groups** cover "
      f"**{sum(shared.values())} oligo records** that share a sequence with at least one other. "
      f"Any outer split must group on `exact_sequence_group`.")
    w("")

    w("## 4. Modelling\n")
    if approved:
        b = approved.get("blocked_model", {})
        w(f"**{b.get('model','')}** — `{b.get('scientist_status','')}` per {b.get('scientist_source','')}.")
        w(f"{b.get('action_taken','')}\n")
        w("Reasons, each checkable against the files here:\n")
        for r in b.get("why_retracted", []): w(f"- {r}")
        w("")
        w("| Authorised lane | Scientist status | Result |")
        w("|---|---|---|")
        la = approved.get("lanes", {}).get("A_matched_contrasts", {})
        lb = approved.get("lanes", {}).get("B_pooled_dose_response", {})
        lcn = approved.get("lanes", {}).get("C_mechanistic_feasibility", {})
        w(f"| Matched-sequence mechanistic contrasts | {la.get('scientist_status','')} | "
          f"{la.get('n_contrasts',0)} contrasts; direction concordance with the scientist's "
          f"independent scores **{la.get('direction_concordance','-')}** |")
        w(f"| Pooled clinical dose-response baseline | {lb.get('scientist_status','')} | "
          f"{len(lb.get('bands',[]))} dose bands described; pooled rows NOT treated as independent |")
        w(f"| Mechanistic proof of concept | {lcn.get('scientist_status','')} | "
          f"{lcn.get('n_eligible_constructs',0)} eligible constructs across "
          f"{lcn.get('n_independent_exact_sequence_groups',0)} independent sequence groups; "
          f"training performed: {lcn.get('training_performed')} |")
        w("")
        w("The strongest defensible result in this dataset is the direction concordance above:")
        w("two independently built datasets, under different rubrics, agree on the sign of the")
        w("effect for every matched-sequence contrast. That is a reproducibility statement about")
        w("the contrasts. It is **not** a model performance claim.\n")
    else:
        w("`data/approved_analyses.json` not built — run `scripts/model_demo.py`.\n")

    w("## 5. Phase 2 dataset requirements\n")
    w("| Requirement | Coverage | Note |")
    w("|---|---:|---|")
    w(f"| sequences of all oligos tested | {nseq}/{len(oligos)} ({100*nseq//max(len(oligos),1)}%) | rest TBD, never guessed |")
    w(f"| location of all chemical modifications | {nmap}/{len(oligos)} ({100*nmap//max(len(oligos),1)}%) | "
      f"per-residue maps; {len(recoveries)} recovered this round from the scientist package |")
    w(f"| purity and characterization data | {npur}/{len(oligos)} ({100*npur//max(len(oligos),1)}%) | "
      "**OPEN**. Not reported in any source curated so far, including the scientist package, "
      "which records `NOT REPORTED IN CURRENT CORPUS` for all 45 of its records. Recorded as "
      "TBD, never inferred from a patent or a reference identity. |")
    w("| data dictionary / schema | yes | `schema.md` |")
    w("| CC licence | yes | see `README.md` |")
    w("")
    rec = rd(os.path.join(DATA, "recovery_ledger.csv"))
    if rec:
        crit = [r for r in rec if r.get("priority") == "critical"]
        w("## 5b. Known gaps with a recovery plan\n")
        w(f"`data/recovery_ledger.csv` holds **{len(rec)} entries** ({len(crit)} critical), each "
          "with the missing item, the sources already searched, the next action, a stopping "
          "criterion and an owner. The largest are compounds whose chemistry class the dataset's "
          "own hypothesis depends on:\n")
        w("| Priority | Missing | Next action |")
        w("|---|---|---|")
        for r in crit[:8]:
            w(f"| {r['priority']} | {r['missing_item'][:70]} | {r['next_action'][:90]} |")
        w("")

    w("## 6. What is blocking release\n")
    w("1. **Study registry incomplete** — the human trial count is not yet established, so no")
    w("   trial total may be published.")
    w("2. **Purity / characterization unresolved** — an explicit Phase 2 requirement with 0%")
    w("   coverage. A recovery plan is recorded rather than a claim of impossibility.")
    w("3. **Scientist approval outstanding** — every clinical eligibility is PROVISIONAL and")
    w("   gate SRQ-TMB-012 has not cleared.")
    w("4. **No qualified clinical negatives** — any clinical modelling claim must state this")
    w("   limit rather than manufacture class balance from reporting silence.")
    w("")
    if conflicts:
        w("## 7. Decisions requiring scientific review\n")
        w("| Kind | Compound | Scientist value | Branch value |")
        w("|---|---|---|---|")
        for c in conflicts[:20]:
            w(f"| {c['kind']} | {c['compound']} | {c['scientist_value'][:40]} | {c['branch_value'][:40]} |")
        w("")

    out = os.path.join(ENDPOINT, "STATUS.md")
    open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(f"wrote STATUS.md  ({len(L)} lines)")
    print(f"  human clinical records {hc} · human lab {hl} · animal {an} · unresolved {ur}")
    print(f"  trial count: {trial_state[:60]}")
    print(f"  scientist-adjudicated {adj}/{len(oligos)} · clinical-eligible {len(elig)} · mechanistic {len(mech)}")


if __name__ == "__main__":
    main()
