#!/usr/bin/env python3
"""Regenerate every generated section of thrombocytopenia/README.md from the data.

Two sections of the README are derived, not written: the record counter and the
fitness-for-purpose analysis. Both are delimited by HTML comment markers and are
rewritten in place from the canonical CSVs, so documented numbers cannot drift
away from the dataset they describe — a failure mode that is easy to introduce
and hard to notice, because a stale table looks exactly like a fresh one.

Run this after every ingestion round, together with build_merged_thrombo.py.

Usage:  python3 scripts/refresh_docs.py
"""
import os, subprocess, sys

# Paths are anchored to the ENDPOINT folder that owns this script, so all
# thrombocytopenia artefacts stay inside thrombocytopenia/ and nothing is
# written outside it.
ENDPOINT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README = os.path.join(ENDPOINT, "README.md")
SCRIPTS = os.path.dirname(os.path.abspath(__file__))

NOTE = ("*Generated by `scripts/report_thrombo.py` and regenerated after every "
        "ingestion round, so the documented numbers cannot drift from the data.*\n\n")


def run(script, *args):
    r = subprocess.run([sys.executable, os.path.join(SCRIPTS, script), *args],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"{script} failed:\n{r.stderr}")
    return r.stdout


def splice(text, begin, end, body):
    if begin not in text or end not in text:
        sys.exit(f"marker {begin} / {end} missing from README — cannot splice")
    return text[:text.index(begin) + len(begin)] + "\n\n" + body.rstrip() + "\n\n" + text[text.index(end):]


def main():
    # 1. record counter — keep the counter and distribution tables, drop the long
    #    per-readout / per-source listings, which belong in the report not the README
    rep = run("report_thrombo.py")
    cut = rep.find("## Top readouts")
    counter = NOTE + (rep[:cut] if cut > 0 else rep).rstrip()

    # 2. fitness-for-purpose analysis
    ana = run("analyze_thrombo.py", "--markdown")
    marker = "**Backbone chemistry orders"
    if marker not in ana:
        sys.exit("analyze_thrombo.py --markdown produced no analysis block")
    fitness = ana[ana.index(marker):].rstrip()

    t = open(README, encoding="utf-8").read()
    t = splice(t, "<!-- BEGIN RECORD COUNTER -->", "<!-- END RECORD COUNTER -->", counter)
    t = splice(t, "<!-- BEGIN FITNESS ANALYSIS -->", "<!-- END FITNESS ANALYSIS -->", fitness)
    open(README, "w", encoding="utf-8").write(t)

    print("refreshed README record counter + fitness analysis")


if __name__ == "__main__":
    main()
