#!/usr/bin/env python3
"""Generate SUMMARY.md — the one-page consolidated summary of the CNS module.

    python3 src/make_summary.py

Every number is read from qc/validate_dataset.py --json and figures/baseline_model.json at
generation time, so this file cannot drift from the dataset it describes. Do not hand-edit.
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main() -> int:
    q = json.loads(subprocess.run([sys.executable, str(ROOT / "qc" / "validate_dataset.py"),
                                   "--json"], capture_output=True, text=True).stdout)
    n = q["summary"]
    m = json.loads((ROOT / "figures" / "baseline_model.json").read_text())
    g = n["grade_distribution"]
    sd = n["study_type_distribution"]
    pct = lambda a, b: f"{100 * a / b:.1f}%"

    md = f"""# OligoTox-CNS — summary

**CNS / neurotoxicity module** of the NIH/NCATS Oligonucleotide Toxicity Open Data Challenge,
Phase 2. Release **v1.0**. Licence **CC BY 4.0** (see `LICENSE.md` for the per-row breakdown).

*Generated by `src/make_summary.py` from the data. Do not hand-edit — regenerate.*

---

## The dataset in one table

| | |
|---|---|
| Oligonucleotides | **{n['n_oligos']:,}** |
| CNS toxicity measurements | **{n['n_measurements']:,}** |
| Per-position chemical-modification records | **{n['n_modification_rows']:,}** |
| Sources | **{n['n_sources']}** — 4 contributing rows, 1 contributing measurement instruments only |
| Sequences published | {n['sequences_present']:,} / {n['n_oligos']:,} ({pct(n['sequences_present'], n['n_oligos'])}) |
| Position-resolved modification maps | {n['position_resolved_oligos']:,} / {n['n_oligos']:,} ({pct(n['position_resolved_oligos'], n['n_oligos'])}) |
| Structural QC | **{n['checks_passed']}/{n['checks_total']} checks pass** |

Split across the three endpoint folders, none of which mixes toxicities:

| Endpoint folder | Measurements | On the brief's list? |
|---|---:|---|
| `toxicity/acute-neurotoxicity/` | {n['measurements_per_endpoint']['acute-neurotoxicity']:,} | **no** — the deprioritised axis, plus general clinical CNS AEs |
| `toxicity/chronic-neurotoxicity/` | {n['measurements_per_endpoint']['chronic-neurotoxicity']} | yes |
| `toxicity/hydrocephalus/` | {n['measurements_per_endpoint']['hydrocephalus']} | yes |

**Severity grades 0/1/2/3** — {g.get('0',0)} / {g.get('1',0)} / {g.get('2',0)} / {g.get('3',0)}.
**Study types** — {sd.get('in_vitro',0):,} in vitro, {sd.get('animal_invivo',0)} in vivo, {sd.get('clinical',0)} clinical.

## What makes it useful

Every row pairs an oligonucleotide's **design** — its sequence and the position of every chemical
modification in it — with a **measured CNS toxicity outcome**. That pairing is what a predictive
model needs, and it did not previously exist in one place for the CNS.

- **{m['n_both']} compounds carry paired in vitro and in vivo readouts** — the in-vitro-to-in-vivo
  extrapolation the challenge asks for.
- **All four severity grades are populated**, including {g.get('0',0)} grade-0 rows and 13 designed
  guanine-free negative controls, so a classifier has a negative class.
- **Four mechanistically distinct toxicity axes** are kept separate rather than collapsed into one
  toxic/not label.
- **Nothing is invented.** Where the literature is silent the field reads `NOT_REPORTED`, and the
  completeness report counts those explicitly.

## Findings

1. **The field's largest public CNS dataset is ~12× bigger than it is usually cited as.** Hagedorn
   2022 is cited for 148 mouse-dosed compounds; its supplementary table holds **1,825**, each with
   a sequence encoding LNA position. Restructuring the full table is this module's main contribution.
2. **Sequence predicts in vivo toxicity better than the in vitro assay does** —
   AUC **{m['auc_all_published_linear']}** vs **{m['auc_all_measured_invitro']}** across all {m['n_both']} paired compounds.
3. **The in vitro assay's noise is measurable from the data: CV 17.3%** (one control oligo, 14
   independent plate runs). That explains finding 2.
4. **Guanine is a graded risk factor and position beats count** — median mouse score rises 0.3 → 20
   with guanine count; a guanine near the 3′ end is the strongest single warning.
5. **Formulation can override sequence entirely** — added calcium takes the same molecule from
   19.5 to 1.0 on a 0–20 scale.
6. **Two 2024–2026 sources contradict each other** on cation rescue, because they score different
   phenotypes. Only visible with sources side by side.
7. **Acute screening misses late-onset toxicity** — compounds with no acute signal cause motor loss
   from day 3, severe enough to require humane sacrifice.

## Predictive-model evidence

Demonstrated, not asserted (`src/baseline_model.py`, trained on the source's own split; the
held-out set is {m['n_held']} compounds against a **different target gene**):

| model | held-out AUC | held-out accuracy |
|---|---|---|
| published linear model (sequence only) | {m['auc_published_linear']} | **{m['acc_published_cutoff70']:.1%}** |
| measured in vitro assay | {m['auc_measured_invitro']} | — |
| logistic regression fitted here, 12 features | {m['auc_logistic_12feat']} | {m['acc_logistic']:.1%} |

The published model reproduces the accuracy its authors report, confirming the restructured table
is faithful. A richer model **did not beat it** — the constraint is labelled in vivo examples, not
features.

## Limitations, stated plainly

- **Per-compound purity is absent from the literature.** `purity_pct` is `NOT_REPORTED` for all
  {n['missingness']['purity_pct']:,} oligonucleotides; the purification *method* is captured for
  {n['n_oligos'] - n['missingness']['purity_method']:,}. Nothing was estimated to close this.
- **The in vitro arm is rat, not human.** Only {n['human_system_measurements']} of
  {n['n_measurements']:,} measurements are human-derived, and all are clinical. No public,
  sequence-resolved human iPSC/organoid oligo-CNS dataset was found.
- **Chemistry is narrow** — the core is one class (LNA/DNA full-phosphorothioate) from one study.
- **Grades are provisional**, pending subject-matter-expert review.
- **One row is one group, not one animal** (group means over 4–6 mice).

## Where everything is

| | |
|---|---|
| Dataset | one per endpoint: `toxicity/{{acute,chronic}}-neurotoxicity/data/` and `toxicity/hydrocephalus/data/` — each holds only its own toxicity |
| Endpoint allocation rule | `src/endpoints.py` — enforced by four QC checks |
| Submission PDFs | `deliverables/OligoTox-CNS_{{Narrative,Methodology}}.pdf` |
| Dataset workbook | `deliverables/OligoTox-CNS_Dataset.xlsx` |
| Schema & dictionary | `docs/SCHEMA.md`, `docs/DATA_DICTIONARY.md` |
| Measurement scales | `docs/SCORING_INSTRUMENTS.md` |
| Access plan | `docs/PADP.md` · Licence `LICENSE.md` |
| Findings with number traces | `FINDINGS.md` |
| Build log and errors caught | `CHANGES.md` |
| Open decisions | `OPEN_ITEMS.md` |
| Source register / v1.1 queue | `sources/RESEARCH_QUEUE.md` |

## Open decisions for the team

- **OI-05** — confirm a *curated* (not wet-lab-generated) module is what is wanted for Phase 2.
- **OI-06** — confirm deliverable filenames match what the submission portal expects.
- **OI-07** — the human *in vitro* layer the challenge prioritises does not appear to exist
  publicly; closing it would mean generating data, not curating it.
- **OI-08** — the cation-rescue contradiction needs a domain expert to confirm the reconciliation.
"""
    (ROOT / "SUMMARY.md").write_text(md)
    print(f"wrote SUMMARY.md ({len(md.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
