#!/usr/bin/env python3
"""Generate SUMMARY.md and LICENSE.md — the two files that must never drift from the data.

    python3 src/make_summary.py

Every number is read from qc/validate_dataset.py --json, figures/baseline_model.json and the
source registry in src/assemble.py at generation time, so neither file can state a figure the
dataset does not support. LICENSE.md in particular was hand-written until a source audit found
it quoting row counts from a release three revisions old, while two sources had also been
recorded under the wrong licence. Both files are generated now. Do not hand-edit.
"""
from __future__ import annotations

import collections
import csv
import json
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import endpoints
from assemble import SOURCES

ROOT = pathlib.Path(__file__).resolve().parent.parent

# What each redistribution class actually permits. The wording is the operative permission, not a
# summary of it, so it is stated once here and reused wherever the class appears.
PERMITS = {
    "cc_by": "any use, including commercial, with attribution",
    "public_domain": "any use, no conditions",
    "cc_by_nc": "non-commercial use only, with attribution",
    "summary_stat_only": "cite and read; the source licence carries a NoDerivatives clause, so "
                         "these rows are not offered for redistribution as dataset content",
}
LICENCE_TEXT = {
    "cc_by": "https://creativecommons.org/licenses/by/4.0/legalcode",
    "cc_by_nc": "https://creativecommons.org/licenses/by-nc/4.0/legalcode",
    "summary_stat_only": "https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode",
}


def write_license(meas: list[dict], oligos: list[dict]) -> str:
    """LICENSE.md, with every count computed from the rows themselves."""
    by_class = collections.Counter(m["redistribution"] for m in meas)
    total = len(meas)
    src_of_class = collections.defaultdict(list)
    for s in SOURCES:
        # a source only appears in the table if it actually contributed rows
        if any(m["source_id"] == s["source_id"] for m in meas):
            src_of_class[s["redistribution"]].append(s)

    open_rows = sum(v for k, v in by_class.items() if k in ("cc_by", "public_domain"))
    open_oligo_ids = {m["oligo_id"] for m in meas if m["redistribution"] in ("cc_by", "public_domain")}
    restricted = total - open_rows
    pc = lambda a: f"{100 * a / total:.1f} %"

    order = ["cc_by", "public_domain", "cc_by_nc", "summary_stat_only"]
    rows = []
    for cls in order:
        if not by_class.get(cls):
            continue
        srcs = "; ".join(f"{s['source_id']} — {s['first_author']} {s['year']}, {s['license']}"
                         for s in src_of_class[cls])
        rows.append(f"| `{cls}` | {srcs} | {by_class[cls]:,} | {PERMITS[cls]} |")
    table = "\n".join(rows)

    md = f"""# Licence and terms of use — OligoTox-CNS

*Generated by `src/make_summary.py` from the released rows and the source registry in
`src/assemble.py`. Do not hand-edit — regenerate.*

## Short version

- Everything **we** created — the schema, the code, the documentation, the figures, and every
  computed or derived field — is released under **Creative Commons Attribution 4.0
  International (CC BY 4.0)**.
- The **row-level scientific content** is curated from published sources, and each row carries
  the terms of the source it came from in its `redistribution` column.
- **{open_rows:,} of {total:,} measurements ({pc(open_rows)}) are CC BY 4.0 or US public domain**
  and may be reused for any purpose, including commercially, with attribution.
- **{restricted:,} measurements ({pc(restricted)})** come from sources whose licence is narrower.
  They are individually marked and can be excluded with one filter.

Nothing here is behind a registration wall, a data-use agreement, or an access committee. The
files are plain CSV and XLSX.

---

## Why the licence is mixed, and how to work with it

A curated dataset cannot grant rights the underlying publications did not grant. Rather than
either over-claiming (labelling everything CC BY) or under-claiming (labelling everything
non-commercial, which would needlessly restrict {pc(open_rows)} of the data), each row states
its own terms.

| `redistribution` | source | rows | what you may do |
|---|---|---|---|
{table}

`summary_stat_only` is the strictest class and exists because two sources are licensed
**CC BY-NC-ND**. NoDerivatives means the article may be redistributed only unadapted; extracting
its numbers into a differently-shaped table is an adaptation. Those rows are therefore published
here as a pointer to the source and its exact location, and users who need the values should read
them from the source itself. Every such row still carries its full `source_ref` and
`source_location`, so this costs traceability nothing.

### To obtain a fully commercially-reusable subset

```python
import csv
rows = list(csv.DictReader(open("data/measurements.csv")))
open_rows = [r for r in rows if r["redistribution"] in ("cc_by", "public_domain")]
# {open_rows:,} of {total:,} measurements, covering {len(open_oligo_ids):,} of {len(oligos):,} oligonucleotides
```

The scientific core of the release — the sequence-resolved oligonucleotides with paired
in vitro and in vivo readouts — is entirely within the CC BY portion.

---

## Attribution

If you use this dataset, please cite **both** this dataset and the primary sources whose data
you used. `data/sources.csv` carries the full citation, DOI, PMCID and licence for each, and
`deliverables/OligoTox-CNS_SourceRegister.pdf` states, source by source, which database each
file came from and exactly which table or figure inside it was read.

Suggested dataset citation:

> OligoTox-CNS: an open, sequence-resolved dataset of central-nervous-system toxicity for
> oligonucleotide therapeutics. Assembled for the NIH/NCATS Oligonucleotide Toxicity
> Open Data Challenge, Phase 2.

The single largest contributing source, and the one any user of this dataset must cite:

> Hagedorn PH, Brown JM, Easton A, Pierdomenico M, Jones K, Olson RE, Mercer SE, Li D, Loy J,
> Høg AM, Jensen ML, Gill M, Cacace AM. Acute Neurotoxicity of Antisense Oligonucleotides After
> Intracerebroventricular Injection Into Mouse Brain Can Be Predicted from Sequence Features.
> *Nucleic Acid Therapeutics*. 2022 Jun;32(3):151–162. doi:10.1089/nat.2021.0071.
> PMID 35166597. PMC9221153. Licensed CC BY 4.0.

---

## Disclaimer

This is a research dataset assembled from published literature and regulatory documents. It is
not medical advice, not a regulatory submission, and not a substitute for reading the primary
sources. All severity grades are **provisional** and await subject-matter-expert review; see
`OPEN_ITEMS.md`. Where a value was not published, it is marked `NOT_REPORTED` rather than
estimated — users should treat those fields as genuinely unknown, not as zero.

Full licence texts:
CC BY 4.0 — {LICENCE_TEXT['cc_by']}
CC BY-NC 4.0 — {LICENCE_TEXT['cc_by_nc']}
CC BY-NC-ND 4.0 — {LICENCE_TEXT['summary_stat_only']}
"""
    (ROOT / "LICENSE.md").write_text(md)
    return md


def main() -> int:
    q = json.loads(subprocess.run([sys.executable, str(ROOT / "qc" / "validate_dataset.py"),
                                   "--json"], capture_output=True, text=True).stdout)
    n = q["summary"]
    m = json.loads((ROOT / "figures" / "baseline_model.json").read_text())
    g = n["grade_distribution"]
    sd = n["study_type_distribution"]
    sc = n["subject_class_distribution"]
    pct = lambda a, b: f"{100 * a / b:.1f}%"

    md = f"""# OligoTox-CNS — summary

**CNS / neurotoxicity module** of the NIH/NCATS Oligonucleotide Toxicity Open Data Challenge,
Phase 2. Release **v1.0**. Licence **CC BY 4.0** (see `LICENSE.md` for the per-row breakdown).

*Generated by `src/make_summary.py` from the data. Do not hand-edit — regenerate.*

---

## The dataset in one table

| | |
|---|---|
| Oligonucleotides | **{n['n_oligos']:,}** |
| CNS toxicity measurements | **{n['n_measurements']:,}** |
| Per-position chemical-modification records | **{n['n_modification_rows']:,}** |
| Sources | **{n['n_sources']}** — 4 contributing rows, 1 contributing measurement instruments only |
| Sequences published | {n['sequences_present']:,} / {n['n_oligos']:,} ({pct(n['sequences_present'], n['n_oligos'])}) |
| Position-resolved modification maps | {n['position_resolved_oligos']:,} / {n['n_oligos']:,} ({pct(n['position_resolved_oligos'], n['n_oligos'])}) |
| Structural QC | **{n['checks_passed']}/{n['checks_total']} checks pass** |

Split across the three endpoint folders, none of which mixes toxicities:

| Endpoint folder | Measurements | On the brief's list? |
|---|---:|---|
| `toxicity/acute-neurotoxicity/` | {n['measurements_per_endpoint']['acute-neurotoxicity']:,} | **no** — the deprioritised axis, plus general clinical CNS AEs |
| `toxicity/chronic-neurotoxicity/` | {n['measurements_per_endpoint']['chronic-neurotoxicity']} | yes |
| `toxicity/hydrocephalus/` | {n['measurements_per_endpoint']['hydrocephalus']} | yes |

### Human versus animal — the division the brief singles out

The Challenge brief prioritises datasets *"based on in vitro human systems or able to extrapolate
data between in vitro human systems and animal data"*. Each endpoint folder therefore carries
`measurements_human.csv` and `measurements_animal.csv` alongside the full table, and every row
declares a `subject_class`:

| subject class | rows | what it is |
|---|---:|---|
| `human_clinical` | {sc['human_clinical']} | adverse events in dosed patients |
| `human_invitro` | **{sc['human_invitro']}** | **human-derived cells — the class the brief prioritises, and it is empty** |
| `animal_invivo` | {sc['animal_invivo']} | dosed mice and rats |
| `animal_invitro` | {sc['animal_invitro']} | rat primary cortical neurons |

**Stated plainly: this dataset contains no human in vitro data at all**, and both halves of the
brief's priority require it — "based on in vitro human systems" *or* "able to extrapolate data
between in vitro human systems and animal data". **On a strict reading the dataset satisfies
neither.**

What it does have is the *structure* that clause asks for, one species short: {m['n_both']}
compounds carry paired in vitro and in vivo readouts on the same molecules, so the
extrapolation machinery — matched compounds, matched grading, a measured assay-noise floor — is
built and working. It is rat-in-vitro to mouse-in-vivo, an animal-to-animal bridge. Substituting a
human in vitro arm would make it the bridge the brief actually asks for, and is the single highest-
value addition available to this module.

**Severity grades 0/1/2/3** — {g.get('0',0)} / {g.get('1',0)} / {g.get('2',0)} / {g.get('3',0)}.
**Study types** — {sd.get('in_vitro',0):,} in vitro, {sd.get('animal_invivo',0)} in vivo, {sd.get('clinical',0)} clinical.

## What makes it useful

Every row pairs an oligonucleotide's **design** — its sequence and the position of every chemical
modification in it — with a **measured CNS toxicity outcome**. That pairing is what a predictive
model needs, and it did not previously exist in one place for the CNS.

- **{m['n_both']} compounds carry paired in vitro and in vivo readouts** — the in-vitro-to-in-vivo
  extrapolation the challenge asks for.
- **All four severity grades are populated**, including {g.get('0',0)} grade-0 rows and 13 designed
  guanine-free negative controls, so a classifier has a negative class.
- **Four mechanistically distinct toxicity axes** are kept separate rather than collapsed into one
  toxic/not label.
- **Nothing is invented.** Where the literature is silent the field reads `NOT_REPORTED`, and the
  completeness report counts those explicitly.

## Findings

1. **The field's largest public CNS dataset is ~12× bigger than it is usually cited as.** Hagedorn
   2022 is cited for 148 mouse-dosed compounds; its supplementary table holds **1,825**, each with
   a sequence encoding LNA position. Restructuring the full table is this module's main contribution.
2. **Sequence predicts in vivo toxicity better than the in vitro assay does** —
   AUC **{m['auc_all_published_linear']}** vs **{m['auc_all_measured_invitro']}** across all {m['n_both']} paired compounds.
3. **The in vitro assay's noise is measurable from the data: CV 17.3%** (one control oligo, 14
   independent plate runs). That explains finding 2.
4. **Guanine is a graded risk factor and position beats count** — median mouse score rises 0.3 → 20
   with guanine count; a guanine near the 3′ end is the strongest single warning.
5. **Formulation can override sequence entirely** — added calcium takes the same molecule from
   19.5 to 1.0 on a 0–20 scale.
6. **Two 2024–2026 sources contradict each other** on cation rescue, because they score different
   phenotypes. Only visible with sources side by side.
7. **Acute screening misses late-onset toxicity** — compounds with no acute signal cause motor loss
   from day 3, severe enough to require humane sacrifice.

## Predictive-model evidence

Demonstrated, not asserted (`src/baseline_model.py`, trained on the source's own split; the
held-out set is {m['n_held']} compounds against a **different target gene**):

| model | held-out AUC | held-out accuracy |
|---|---|---|
| published linear model (sequence only) | {m['auc_published_linear']} | **{m['acc_published_cutoff70']:.1%}** |
| measured in vitro assay | {m['auc_measured_invitro']} | — |
| logistic regression fitted here, 12 features | {m['auc_logistic_12feat']} | {m['acc_logistic']:.1%} |

The published model reproduces the accuracy its authors report, confirming the restructured table
is faithful. A richer model **did not beat it** — the constraint is labelled in vivo examples, not
features.

## Limitations, stated plainly

- **Per-compound purity is absent from the literature.** `purity_pct` is `NOT_REPORTED` for all
  {n['missingness']['purity_pct']:,} oligonucleotides; the purification *method* is captured for
  {n['n_oligos'] - n['missingness']['purity_method']:,}. Nothing was estimated to close this.
- **The in vitro arm is rat, not human.** Only {n['human_system_measurements']} of
  {n['n_measurements']:,} measurements are human-derived, and all are clinical. No public,
  sequence-resolved human iPSC/organoid oligo-CNS dataset was found.
- **Chemistry is narrow** — the core is one class (LNA/DNA full-phosphorothioate) from one study.
- **Grades are provisional**, pending subject-matter-expert review.
- **One row is one group, not one animal** (group means over 4–6 mice).

## Where everything is

| | |
|---|---|
| Dataset | one per endpoint: `toxicity/{{acute,chronic}}-neurotoxicity/data/` and `toxicity/hydrocephalus/data/` — each holds only its own toxicity |
| Endpoint allocation rule | `src/endpoints.py` — enforced by four QC checks |
| Submission PDFs | `deliverables/OligoTox-CNS_{{Narrative,Methodology}}.pdf` |
| Dataset workbook | `deliverables/OligoTox-CNS_Dataset.xlsx` |
| Schema & dictionary | `docs/SCHEMA.md`, `docs/DATA_DICTIONARY.md` |
| Measurement scales | `docs/SCORING_INSTRUMENTS.md` |
| Access plan | `docs/PADP.md` · Licence `LICENSE.md` |
| Findings with number traces | `FINDINGS.md` |
| Build log and errors caught | `CHANGES.md` |
| Open decisions | `OPEN_ITEMS.md` |
| Source register / v1.1 queue | `sources/RESEARCH_QUEUE.md` |

## Open decisions for the team

- **OI-05** — confirm a *curated* (not wet-lab-generated) module is what is wanted for Phase 2.
- **OI-06** — confirm deliverable filenames match what the submission portal expects.
- **OI-07** — the human *in vitro* layer is open on scale, not existence: 34 rows are in, eight
  further sources are identified with verified identifiers and none is extracted yet.
- **OI-08** — the cation-rescue contradiction needs a domain expert to confirm the reconciliation.
"""
    (ROOT / "SUMMARY.md").write_text(md)
    print(f"wrote SUMMARY.md ({len(md.splitlines())} lines)")

    lic = write_license(endpoints.load_all("measurements"), endpoints.load_all("oligos"))
    print(f"wrote LICENSE.md ({len(lic.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
