#!/usr/bin/env python3
"""Generate the four evidence reports that answer Beebop's 2026-09-30 proposals.

    python3 src/make_evidence_reports.py

    docs/TRIAL_REGISTER.md            human-first counting: trials, cohorts, rows, compounds
    docs/CHRONIC_QUALIFICATION.md     what the sources can and cannot establish about chronicity
    docs/TRANSLATIONAL_PAIRING.md     which compounds actually bridge systems, computed
    docs/CHARACTERIZATION_COVERAGE.md completeness, human subset and animal subset kept apart

Every figure is computed here from the released endpoint tables at generation time. These four
documents exist because the same four questions kept being answered from memory, from a stale
README, or from a pooled figure that let the 1,825-compound rat screen stand in for human
completeness. A generated answer cannot do any of those things.
"""
from __future__ import annotations

import collections
import csv
import json
import pathlib
import re
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import endpoints

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
HUMAN = {"human_clinical", "human_invitro"}


def load():
    meas = endpoints.load_all("measurements")
    oligos = endpoints.load_all("oligos")
    trials = []
    seen = set()
    for ep in endpoints.ENDPOINTS:
        f = endpoints.data_dir(ep) / "trials.csv"
        if f.exists():
            for r in csv.DictReader(f.open()):
                if r["trial_key"] not in seen:
                    seen.add(r["trial_key"])
                    trials.append(r)
    return meas, oligos, trials


# ==============================================================================================
def trial_register(meas, oligos, trials) -> str:
    ev = [t for t in trials if t["endpoint_evaluable"] == "TRUE"]
    idx = [t for t in ev if t["cohort_role"] == "index_cohort"]
    ext = [t for t in ev if t["cohort_role"] == "extension_study"]
    clin = [m for m in meas if m["study_type"] == "clinical"]
    active = [m for m in clin if m["arm_role"] == "active"]
    ctrl = [m for m in clin if m["arm_role"] == "placebo_or_sham"]
    spont = [m for m in clin if m["arm_role"] == "spontaneous_report"]
    zero = [m for m in clin if m["incidence_is_zero"] == "TRUE"]
    lab = [m for m in meas if m["subject_class"] == "human_invitro"]
    compounds = sorted({t["compound"] for t in ev})
    idx_enrol = sum(int(t["enrollment_count"]) for t in idx if t["enrollment_count"].isdigit())
    all_enrol = sum(int(t["enrollment_count"]) for t in ev if t["enrollment_count"].isdigit())

    rows = "\n".join(
        f"| `{t['nct_id']}` | {t['compound']} | {t['phase']} | {t['allocation'].title()} | "
        f"{t['cohort_role'].replace('_', ' ')} | {t['enrollment_count']} | {t['n_cns_measurements']} |"
        for t in sorted(ev, key=lambda x: (x["cohort_role"], x["nct_id"])))

    return f"""# Human evidence register — OligoTox-CNS

*Generated by `src/make_evidence_reports.py` from the released endpoint tables. Do not hand-edit.*

Oscar's counting rule is that a headline clinical-trial total counts **verified, deduplicated,
actual human clinical trials** — never measurement rows, papers, participants, labels, cases,
spontaneous reports or animal experiments. This document is the only place a human count in this
module may be taken from, and every figure below is a different thing from every other.

## The five counts, kept apart

| What | Count | What it is, exactly |
|---|---:|---|
| **Verified unique human trials** | **{len(ev)}** | ClinicalTrials.gov interventional records with posted results contributing ≥1 CNS outcome row |
| **…of which independent enrolling cohorts** | **{len(idx)}** | the rest are extension studies that re-enrol people who finished a parent trial |
| **…of which extension studies** | **{len(ext)}** | their participants are **not** additional people |
| **Human clinical outcome rows** | **{len(clin):,}** | one MedDRA term in one trial arm. **Not** trials, **not** patients |
| **Unique human compounds** | **{len(compounds)}** | {", ".join(compounds)} |
| **Human laboratory experiments** | **{len(lab)}** | human *in vitro*; see `docs/CHARACTERIZATION_COVERAGE.md`. **Not** clinical trials |

## Participant denominators are not additive

Summing enrolment across these trials **double counts people**. The naive sum over all
{len(ev)} evaluable records is **{all_enrol:,}**; the sum over the {len(idx)} index cohorts alone
is **{idx_enrol:,}**. Neither is a unique-participant count, and a unique-participant count is
**not derivable** from registry data — no participant-level identifier exists in any of the
retrieved records. Publish {idx_enrol:,} only with the words "index-cohort enrolment", never as
"patients studied".

## What the {len(clin):,} clinical rows actually are

| | rows |
|---|---:|
| Active treatment arms | {len(active):,} |
| **Placebo / sham comparator arms** | **{len(ctrl):,}** |
| Post-marketing spontaneous reports (no trial, no denominator) | {len(spont)} |
| **…of all rows, those recording that the event did NOT occur** | **{len(zero):,}** |

Two of these need stating plainly because both have been misread before.

**{len(ctrl):,} rows are comparator-arm events.** They are filed under the active compound's
`oligo_id` because that is the trial they belong to — so any group-by on `oligo_id` that ignores
`arm_role` pools placebo events into the drug's event rate. Always filter on
`arm_role == 'active'` before computing an incidence attributable to a compound.

**{len(zero):,} of the {len(clin):,} rows record an absence.** `numAffected = 0` in that arm.
They are evidence that the event did not occur, which is genuinely valuable — and they are not
adverse events. Any sentence of the form "{len(clin):,} adverse events" is wrong by
{100 * len(zero) / len(clin):.0f}%.

## The register

| NCT | Compound | Phase | Allocation | Cohort role | Enrolment | CNS rows |
|---|---|---|---|---|---:|---:|
{rows}

## Cross-package de-duplication

`trial_key` is stable across every package in this submission. The hydrocephalus endpoint draws
rows from trials that also feed chronic neurotoxicity, and the separate hydrocephalus package on
its own branch draws from the same registry records. A consolidated entry must join on
`trial_key` and count each trial **once**, or it will report the same study several times over.
"""


# ==============================================================================================
def chronic_qualification(meas) -> str:
    dist = collections.Counter(m["chronic_qualification"] for m in meas)
    clin = [m for m in meas if m["study_type"] == "clinical"]
    return f"""# Chronic qualification — what the sources can and cannot establish

*Generated by `src/make_evidence_reports.py`. Do not hand-edit.*

Beebop asked for a documented rubric that separates genuinely chronic findings from acute events
during a long trial, disease progression, procedure effects and unresolved timing, so that German
can adjudicate them.

**The rubric cannot be built over the clinical rows, and that is a finding about the source rather
than a gap in the work.**

## Why

Every key in a ClinicalTrials.gov adverse-event record was enumerated across all retrieved files.
An event carries exactly:

    term · organSystem · assessmentType · sourceVocabulary · notes (rare)
    stats[] → groupId · numAffected · numAtRisk · numEvents

There is **no onset, no duration, no persistence, no resolution and no time-to-event field at any
level**. The module's `timeFrame` is a collection window for the whole table — one string per
trial — not a property of any event. It is recorded here as `observation_window`, and it is
explicitly **not** an exposure duration: an earlier revision copied it into `exposure_duration`,
which made rows from single-dose arms assert a multi-month exposure the source never stated.

So no per-event chronic/acute split is derivable from the registry at any level of effort. A
rubric applied to these rows would not be separating chronic from acute; it would be manufacturing
a timing judgement out of a term and a count.

## What the column says instead

| `chronic_qualification` | rows | meaning |
|---|---:|---|
| `not_derivable_from_source` | {dist.get('not_derivable_from_source', 0):,} | the source records incidence in a window and nothing about event timing |
| `acute_by_design` | {dist.get('acute_by_design', 0):,} | the experiment measures an acute endpoint by construction |
| `chronic_supported_by_source` | {dist.get('chronic_supported_by_source', 0)} | the source states the timing itself |

The {dist.get('chronic_supported_by_source', 0)} `chronic_supported_by_source` rows are source L1
(Kuroda 2025), which observes onset from day 3 with sacrifice at days 7–21 and reports late-onset
neurodegeneration as its subject. Those are the only rows in this module where a chronic reading
rests on something the source actually stated.

## For German

1. **Does the chronic-neurotoxicity endpoint keep its {len(clin):,} clinical rows?** They are
   human CNS adverse-event incidence, which is valuable and belongs in the module — but filing
   them under *chronic* asserts a timing the source does not support. The alternative is an
   endpoint named for what they are, e.g. *clinical CNS adverse-event incidence*.
2. **Should the ~80% of tolerability rows that are procedural (post-lumbar-puncture syndrome),
   nonspecific (headache, dizziness) or disease progression be separated** from candidate
   drug-attributable neurotoxicity? This is a clinical judgement, not a regex.
3. **Is registry seriousness an acceptable proxy for severity grade 3?** The current rule maps
   the serious-AE table to grade 3. Seriousness is a regulatory reporting category, not a
   calibrated neurotoxicity severity.

None of the three has been decided here. All grades remain `provisional`.
"""


# ==============================================================================================
def translational_pairing(meas, oligos) -> str:
    by_oligo = collections.defaultdict(set)
    for m in meas:
        by_oligo[m["oligo_id"]].add(m["subject_class"])
    both = [o for o, cs in by_oligo.items() if (cs & HUMAN) and (cs - HUMAN)]

    def seqs(classes):
        ids = {m["oligo_id"] for m in meas if m["subject_class"] in classes}
        return {o["oligo_id"]: o["sequence_base"].strip().upper()
                for o in oligos if o["oligo_id"] in ids
                and o["sequence_base"].strip() not in ("", "NOT_REPORTED")}

    hs, as_ = seqs(HUMAN), seqs({"animal_invitro", "animal_invivo"})
    comp = str.maketrans("ACGTU", "TGCAA")
    exact, contained, revcomp = [], [], []
    for hid, h in hs.items():
        for aid, a in as_.items():
            if h == a:
                exact.append((hid, aid))
            elif h in a or a in h:
                contained.append((hid, aid))
            elif h == a.translate(comp)[::-1]:
                revcomp.append((hid, aid))

    n181 = len({m["oligo_id"] for m in meas if m["source_id"] == "H1"
                and m["subject_class"] == "animal_invivo"})
    return f"""# Translational pairing — what actually bridges systems

*Generated by `src/make_evidence_reports.py`. Do not hand-edit.*

The Challenge prioritises datasets *"based on in vitro human systems or able to extrapolate data
between in vitro human systems and animal data."* Both phrases require human cells on one side.

## The 181-compound pairing is animal to animal

{n181} compounds carry both an *in vitro* and an *in vivo* readout. Both sides come from source
H1: rat primary cortical neuron calcium oscillation, paired to mouse intracerebroventricular
tolerability. Both carry `is_human_system = FALSE`.

It is a genuine and useful in-vitro-to-in-vivo bridge, and it is **not** the bridge the Challenge
asks for. Describing it as satisfying the extrapolation clause is an overclaim, and two documents
in this module did so until 2026-10-02.

## Compounds carrying both a human and an animal row

**{len(both)}.**

| test | matches |
|---|---:|
| Oligos with both a human-system and an animal row | {len(both)} |
| Exact `sequence_base` match, human source ↔ animal source | {len(exact)} |
| Containment (one sequence inside the other) | {len(contained)} |
| Reverse complement | {len(revcomp)} |

Compared {len(hs)} sequence-resolved human-system oligos against {len(as_)} animal ones. The
cross-system compound count is zero by every test, so **no compound in this release has its
toxicity measured in both a human and an animal system.** There is nothing to extrapolate between
yet.

## What would close it

The highest-value acquisition is a compound measured in a human system that is *already* in the
clinical layer. **Ottesen 2026** (PMC12805893, CC BY) reports an 18-mer whose sequence and
chemistry are identical to **nusinersen**, which this dataset already holds as a clinical
compound. Extracting it would create the module's first genuine human-laboratory-to-human-clinical
link on a single molecule. It is queued in `sources/RESEARCH_QUEUE.md`.
"""


# ==============================================================================================
def characterization(meas, oligos) -> str:
    reach = collections.defaultdict(set)
    for m in meas:
        reach[m["oligo_id"]].add(m["subject_class"])
    hum = {o for o, c in reach.items() if c & HUMAN}
    ani = {o for o, c in reach.items() if (c - HUMAN) and not (c & HUMAN)}
    idx = {o["oligo_id"]: o for o in oligos}

    FIELDS = [("sequence_5to3_asprinted", "Sequence as printed"),
              ("sequence_base", "Nucleobase sequence"),
              ("modification_positions", "Per-position modification map"),
              ("purity_pct", "Purity value"),
              ("purity_method", "Purification method"),
              ("identity_confirmation", "Analytical identity confirmation")]

    def have(ids, f):
        return sum(1 for i in ids if idx.get(i, {}).get(f, "").strip() not in ("", "NOT_REPORTED"))

    src_res = sum(1 for i in hum
                  if idx.get(i, {}).get("modification_position_basis", "").startswith("position_resolved"))
    src_res_a = sum(1 for i in ani
                    if idx.get(i, {}).get("modification_position_basis", "").startswith("position_resolved"))
    rows = "\n".join(
        f"| {lab} | {have(hum, f)} / {len(hum)} | {100*have(hum,f)/len(hum):.0f}% | "
        f"{have(ani, f):,} / {len(ani):,} | {100*have(ani,f)/len(ani):.0f}% |"
        for f, lab in FIELDS)

    return f"""# Characterization coverage — human subset and animal subset, kept apart

*Generated by `src/make_evidence_reports.py`. Do not hand-edit.*

The Challenge requires, per oligonucleotide, the sequence, the location of all chemical
modifications, purity and identity. **Every completeness figure this module published before
2026-10-02 was pooled**, which let a {len(ani):,}-compound rat screen stand in for human
completeness. Pooled figures are not reported here at all.

| | Human-reaching ({len(hum)}) | | Animal-only ({len(ani):,}) | |
|---|---:|---:|---:|---:|
{rows}
| *of those, source-resolved positions* | {src_res} / {len(hum)} | {100*src_res/len(hum):.0f}% | {src_res_a:,} / {len(ani):,} | {100*src_res_a/len(ani):.0f}% |

## Read this honestly

**The human subset is essentially uncharacterized.** Of the {len(hum)} oligonucleotides that reach
a human measurement, {have(hum, 'sequence_5to3_asprinted')} carry a sequence, **{src_res} carry a
source-resolved modification map**, **{have(hum, 'purity_pct')} carry a purity value** and
**{have(hum, 'identity_confirmation')} carry an identity confirmation**. The mandatory
characterization requirement is currently met for the rat screen and not for the data class the
Challenge is built around.

**Purity is zero everywhere**, in both subsets. A purification *method* is recorded for many
compounds; a purity *value* is recorded for none. These are different things and the distinction
is load-bearing — a method says how the material was cleaned, a value says how clean it was. See
`OPEN_ITEMS.md` OI-02.

**A reference sequence is not analytical identity.** Where a sequence was verified against a
publication or an INN description, that establishes what the compound was *intended* to be. It
says nothing about the purity or identity of the material actually dosed in the experiment.

## Recoverable, with a named lead

| Gap | Lead |
|---|---|
| Purity / identity for the HV compounds | supplementary methods of HV1–HV3; vendor certificates of analysis are not in the public record |
| Modification positions for clinical compounds | the published INN descriptions, which print per-position chemistry formally — this is how tofersen's map was obtained |
| Purity / identity for the clinical compounds | not published; vendor certificates of analysis for an investigational oligonucleotide are not in the public record |

**Closed since the first revision of this report.** HV3's 23 sequences were printed in `mmc1.pdf`
Table S2 in LNA notation (`+N` = LNA, `/IDSP/` = abasic DSpacer) and have been parsed into
per-position maps, with the phosphorothioate backbone transcribed from the source's own wording.
That moved human source-resolved modification coverage off zero.

Nothing above is promised. Each is a specific document that may or may not contain the value.
"""


def main() -> int:
    DOCS.mkdir(parents=True, exist_ok=True)
    meas, oligos, trials = load()
    for name, text in (("TRIAL_REGISTER.md", trial_register(meas, oligos, trials)),
                       ("CHRONIC_QUALIFICATION.md", chronic_qualification(meas)),
                       ("TRANSLATIONAL_PAIRING.md", translational_pairing(meas, oligos)),
                       ("CHARACTERIZATION_COVERAGE.md", characterization(meas, oligos))):
        (DOCS / name).write_text(text)
        print(f"wrote docs/{name} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
