#!/usr/bin/env python3
"""
Predictive analysis of the hydrocephalus endpoint.

This script is deliberately conservative about what it claims. The endpoint is
rare: 9 of 526 trial arms report a tier-A (ventricular) event. Nine events will
not support a sequence-to-toxicity classifier, and presenting one would be
misleading. What the data does support is:

  1. Risk stratification by DELIVERY ROUTE, with exact confidence intervals and
     an exact test, at both arm and participant level.
  2. A modellable secondary outcome — tier B, CSF-dynamics disturbance — which
     occurs in 78 arms and is the mechanistic precursor the index case
     documents.
  3. A LEAKAGE TEST that quantifies how much of any apparent performance comes
     from provenance rather than biology. This is run because a review of the
     sibling kidney dataset found study_type and source_id were strong shortcut
     predictors of its label, and the same hazard applies here.

Validation is leave-one-COMPOUND-out, not random k-fold: arms of the same
compound are correlated, so a random split leaks the compound across folds and
inflates the score.

Outputs: ml/ML_REPORT.md, ml/results.json, ml/figures/*.png
Usage:   python3 ml/analyse.py   (after ml/build_analysis_set.py)
"""
import json
import os
import warnings

import numpy as np
import pandas as pd
from scipy import stats
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

warnings.filterwarnings("ignore")
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
FIG = os.path.join(HERE, "figures")
os.makedirs(FIG, exist_ok=True)

INK, MUTED, ACCENT, WARN = "#1F2933", "#7B8794", "#2C6E9B", "#B4551F"


def wilson(k, n):
    if n == 0:
        return (0.0, 0.0)
    lo, hi = stats.binomtest(k, n).proportion_ci(confidence_level=0.95,
                                                 method="wilson")
    return lo, hi



def write_report(R):
    """Render ml/ML_REPORT.md from the results just computed.

    This function is the correction to a real defect: the module docstring has
    always listed ML_REPORT.md as an output and the report itself opened with
    "Every number here is read from ml/results.json; none is typed" -- but
    nothing wrote it. It was typed by hand, and adding four trials to the
    registry left it asserting 526 arms and 155 trials against a results.json
    that said 546 and 159. A document that claims to be generated must be
    generated.
    """
    st = {}
    sp = os.path.join(os.path.dirname(HERE), "qc", "stats.json")
    if os.path.exists(sp):
        st = json.load(open(sp))
    cns = next(b for b in R["route"] if b["label"].startswith("CNS"))
    sysd = next(b for b in R["route"] if not b["label"].startswith("CNS"))
    by_name = {m["name"]: m for m in R["models"]}

    def auc(name):
        m = by_name.get(name)
        return "%.3f" % m["auc"] if m and m["auc"] is not None else "n/a"

    n_seq = st.get("oligos_with_sequence", 0)
    n_olg = st.get("n_oligos", 0)
    n_vitro = st.get("n_in_vitro_rows", 0)
    vitro_clause = (
        "in vitro-to-in vivo extrapolation beyond the single compound that carries "
        "both (%d in vitro rows in the release)" % n_vitro if n_vitro else
        "in vitro-to-in vivo extrapolation (no in vitro rows exist)")

    md = """# Predictive analysis \u2014 hydrocephalus endpoint

Generated by `ml/analyse.py` from `ml/analysis_set.csv`. Every number here is
read from `ml/results.json`; none is typed.

## The unit of analysis is the trial arm, not the measurement row

`data/measurements.csv` is not a modelling table. Rows within an arm are not
independent \u2014 one arm contributes a row per adverse-event term, and one patient's
episode contributes a row per measurement (that is what `event_cluster_id`
marks). Treating them as independent inflates n by an order of magnitude and
shrinks every interval.

The analysis set aggregates to **one row per (trial, arm)**, which is a binomial
observation with a real denominator: {n_arms:,} arms across {n_trials:,} trials and
{n_compounds} compounds, {n_participants:,} participants at risk. It keeps only
`clinical_trial` rows with a denominator, so every observation is the same kind
of thing.

| | |
|---|---:|
| Arms | {n_arms:,} |
| Trials | {n_trials:,} |
| Compounds | {n_compounds} |
| Participants at risk (arm-sum) | {n_participants:,} |
| Arms with a tier-A (ventricular) event | **{n_armsA}** |
| Arms with a tier-B (CSF-dynamics) event | {n_armsB} |

**{n_armsA} tier-A arms will not support a classifier**, and this report does not
present one. What the data supports is route stratification, a modellable
tier-B outcome, and a leakage diagnosis.

## 1. Route stratifies the endpoint \u2014 between cohorts

| Route | Participants | Affected | Rate / 1,000 | 95% Wilson |
|---|---:|---:|---:|---|
| {cns_label} | {cns_n:,} | {cns_aff} | **{cns_rate:.2f}** | {cns_lo:.2f}\u2013{cns_hi:.2f} |
| {sys_label} | {sys_n:,} | {sys_aff} | {sys_rate:.2f} | {sys_lo:.2f}\u2013{sys_hi:.2f} |

Fisher exact odds ratio **{or_route:.2f}**, p = {p_route:.3g}.

## 2. And the contrast vanishes inside randomised comparisons

Restricting to the {paired_trials} trials carrying their own concurrent
comparator arm:

| | Events | Participants |
|---|---:|---:|
| Treated arms | {t_ev} | {t_n:,} |
| Comparator arms | {c_ev} | {c_n:,} |

Odds ratio **{or_paired:.2f}**, p = {p_paired:.2g}.
**No detectable within-trial effect.**

The two results are not in conflict; they are measuring different things. \u00a71
compares different diseases, ages and monitoring intensities. \u00a72 compares
randomised groups. Reporting \u00a71 alone would be the easiest way to mislead with
this dataset, which is why both are in it.

## 3. Models, and what they actually learn

Outcome: tier-B (CSF-dynamics) event in an arm \u2014 {n_armsB} of {n_arms:,} arms, the
mechanistic precursor the index case documents. Validation is
**leave-one-compound-out**: arms of one compound are correlated, so a random
split leaks the compound across folds and inflates the score.

| Model | LOCO AUC |
|---|---:|
| Route only | {auc_route} |
| **Route + indication** | **{auc_ri}** |
| Route + indication + chemistry | {auc_ric} |
| *Leakage probe: trial identity only* | *{auc_trial}* |
| *Leakage probe: compound identity only* | *{auc_cmpd}* |

Bootstrap 95% CI for the best model: {ci_lo:.3f}\u2013{ci_hi:.3f}.

Three things worth reading off that table:

- **Adding chemistry makes it worse.** Chemistry is `NOT_REPORTED` for most
  compounds, so the feature contributes noise. This is a data-coverage result,
  not a biological one.
- **Trial identity alone reaches {auc_trial}.** A material share of any apparent
  performance is provenance, not biology. We ran this because a review of our
  sibling kidney dataset found `study_type` and `source_id` were strong shortcut
  predictors of its label.
- **Compound identity alone scores {auc_cmpd} \u2014 below chance.** That is the
  *correct* behaviour under leave-one-compound-out and confirms the validation is
  doing its job: a model that knows only which compound a row belongs to cannot
  generalise to a compound it has never seen.

## 4. What this supports, and what it does not

**Supported:** route- and population-stratified risk stratification; separating
drug effect from procedure and disease effect; modelling ascertainment explicitly
as a covariate; hypothesis generation for CSF-dynamics monitoring in intrathecal
programmes.

**Not supported:** sequence-to-toxicity prediction across the roster
({n_seq} of {n_olg} compounds carry a sequence); within-compound dose\u2013response for
tier A; {vitro_clause}; any causal claim about an individual compound, given \u00a72.

## Reproducing

```bash
python3 ml/build_analysis_set.py
python3 ml/analyse.py
```
""".format(
        n_arms=R["n_arms"], n_trials=R["n_trials"], n_compounds=R["n_compounds"],
        n_participants=R["n_participants"], n_armsA=R["n_armsA"],
        n_armsB=R["n_armsB"],
        cns_label=cns["label"], cns_n=cns["participants"],
        cns_aff=cns["participants_affected"], cns_rate=cns["rate_per_1000"],
        cns_lo=cns["ci_lo_per_1000"], cns_hi=cns["ci_hi_per_1000"],
        sys_label=sysd["label"], sys_n=sysd["participants"],
        sys_aff=sysd["participants_affected"], sys_rate=sysd["rate_per_1000"],
        sys_lo=sysd["ci_lo_per_1000"], sys_hi=sysd["ci_hi_per_1000"],
        or_route=R["route_fisher"]["odds_ratio"],
        p_route=R["route_fisher"]["p_value"],
        paired_trials=R["paired_trials"], t_ev=R["paired_treated_events"],
        t_n=R["paired_treated_n"], c_ev=R["paired_ctrl_events"],
        c_n=R["paired_ctrl_n"], or_paired=R["paired_fisher"]["odds_ratio"],
        p_paired=R["paired_fisher"]["p_value"],
        auc_route=auc("route only"), auc_ri=auc("route + indication"),
        auc_ric=auc("route + indication + chemistry"),
        auc_trial=auc("LEAKAGE PROBE: trial identity only"),
        auc_cmpd=auc("LEAKAGE PROBE: compound identity only"),
        ci_lo=R["best_model_auc_ci"][0], ci_hi=R["best_model_auc_ci"][1],
        n_seq=n_seq, n_olg=n_olg, vitro_clause=vitro_clause)

    with open(os.path.join(HERE, "ML_REPORT.md"), "w") as fh:
        fh.write(md)


def main():
    df = pd.read_csv(os.path.join(HERE, "analysis_set.csv"))
    R = {}

    R["n_arms"] = int(len(df))
    R["n_trials"] = int(df.nct_id.nunique())
    R["n_compounds"] = int(df.oligo_name.nunique())
    R["n_participants"] = int(df.n_at_risk.sum())
    R["n_armsA"] = int(df.tierA_event.sum())
    R["n_armsB"] = int(df.tierB_event.sum())

    # ---- 1. route stratification, arm level and participant level ----------
    def block(sub, label):
        arms, ev = len(sub), int(sub.tierA_event.sum())
        pa, pn = int(sub.tierA_affected.sum()), int(sub.n_at_risk.sum())
        lo, hi = wilson(pa, pn)
        return dict(label=label, arms=arms, arms_with_event=ev,
                    participants=pn, participants_affected=pa,
                    rate_per_1000=1000.0 * pa / pn if pn else 0.0,
                    ci_lo_per_1000=1000 * lo, ci_hi_per_1000=1000 * hi)

    cns = df[df.route_is_cns == 1]
    sys_ = df[(df.route_is_cns == 0) & (df.delivery_route != "NOT_REPORTED")]
    R["route"] = [block(cns, "CNS-delivered (intrathecal / ICV)"),
                  block(sys_, "Systemically delivered")]

    tbl = [[int(cns.tierA_affected.sum()),
            int(cns.n_at_risk.sum() - cns.tierA_affected.sum())],
           [int(sys_.tierA_affected.sum()),
            int(sys_.n_at_risk.sum() - sys_.tierA_affected.sum())]]
    odds, p = stats.fisher_exact(tbl)
    R["route_fisher"] = dict(odds_ratio=float(odds), p_value=float(p),
                             table=tbl)

    # ---- 2. per-compound observed tier-A rates -----------------------------
    g = df.groupby("oligo_name").agg(
        arms=("tierA_event", "size"), arms_with_event=("tierA_event", "sum"),
        affected=("tierA_affected", "sum"), at_risk=("n_at_risk", "sum"),
        cns=("route_is_cns", "max")).reset_index()
    g["rate_per_1000"] = 1000 * g.affected / g.at_risk
    g[["lo", "hi"]] = g.apply(
        lambda r: pd.Series([1000 * x for x in wilson(int(r.affected), int(r.at_risk))]),
        axis=1)
    R["by_compound"] = g.sort_values("rate_per_1000", ascending=False).head(14).to_dict("records")

    # ---- 3. within-trial comparator contrast -------------------------------
    # The strongest design available: treated and placebo arms of the SAME trial.
    pairs = []
    for nct, sub in df.groupby("nct_id"):
        tre, com = sub[sub.is_comparator == 0], sub[sub.is_comparator == 1]
        if len(com) == 0 or len(tre) == 0:
            continue
        pairs.append(dict(nct=nct,
                          treated_aff=int(tre.tierA_affected.sum()),
                          treated_n=int(tre.n_at_risk.sum()),
                          ctrl_aff=int(com.tierA_affected.sum()),
                          ctrl_n=int(com.n_at_risk.sum()),
                          cns=int(sub.route_is_cns.max())))
    P = pd.DataFrame(pairs)
    R["paired_trials"] = int(len(P))
    R["paired_treated_events"] = int(P.treated_aff.sum())
    R["paired_ctrl_events"] = int(P.ctrl_aff.sum())
    R["paired_treated_n"] = int(P.treated_n.sum())
    R["paired_ctrl_n"] = int(P.ctrl_n.sum())
    mt = stats.fisher_exact([[P.treated_aff.sum(), P.treated_n.sum() - P.treated_aff.sum()],
                             [P.ctrl_aff.sum(), P.ctrl_n.sum() - P.ctrl_aff.sum()]])
    R["paired_fisher"] = dict(odds_ratio=float(mt[0]), p_value=float(mt[1]))

    # ---- 4. modellable outcome: tier B, with honest validation -------------
    def design(frame, cols):
        X = pd.get_dummies(frame[cols].astype(str), drop_first=False)
        return X.astype(float), list(X.columns)

    def loco(frame, y, cols):
        """Leave-one-compound-out CV. Random folds would leak the compound."""
        preds, truth = [], []
        for comp in frame.oligo_name.unique():
            te = frame.oligo_name == comp
            tr = ~te
            if y[tr].nunique() < 2 or te.sum() == 0:
                continue
            Xtr, names = design(frame[tr], cols)
            Xte, _ = design(frame[te], cols)
            Xte = Xte.reindex(columns=names, fill_value=0.0)
            mdl = LogisticRegression(max_iter=2000, class_weight="balanced", C=1.0)
            mdl.fit(Xtr, y[tr])
            preds.extend(mdl.predict_proba(Xte)[:, 1])
            truth.extend(y[te].tolist())
        if len(set(truth)) < 2:
            return None, len(truth)
        return roc_auc_score(truth, preds), len(truth)

    yB = df.tierB_event
    models = {
        "route only": ["delivery_route"],
        "route + indication": ["delivery_route", "indication"],
        "route + indication + chemistry": ["delivery_route", "indication",
                                           "oligo_class", "backbone_chemistry"],
        "LEAKAGE PROBE: trial identity only": ["nct_id"],
        "LEAKAGE PROBE: compound identity only": ["oligo_name"],
    }
    R["models"] = []
    for name, cols in models.items():
        auc, n = loco(df, yB, cols)
        R["models"].append(dict(name=name, features=cols,
                                auc=None if auc is None else round(float(auc), 3),
                                n_scored=n))

    # bootstrap CI for the best legitimate model
    best = ["delivery_route", "indication"]
    aucs = []
    rng = np.random.default_rng(0)
    for _ in range(300):
        idx = rng.choice(len(df), len(df), replace=True)
        sub = df.iloc[idx].reset_index(drop=True)
        a, _n = loco(sub, sub.tierB_event, best)
        if a is not None:
            aucs.append(a)
    if aucs:
        R["best_model_auc_ci"] = [round(float(np.percentile(aucs, 2.5)), 3),
                                  round(float(np.percentile(aucs, 97.5)), 3)]

    # ---- figures -----------------------------------------------------------
    fig, ax = plt.subplots(figsize=(7.2, 3.4))
    lab = [b["label"].replace(" (", "\n(") for b in R["route"]]
    val = [b["rate_per_1000"] for b in R["route"]]
    err = [[b["rate_per_1000"] - b["ci_lo_per_1000"] for b in R["route"]],
           [b["ci_hi_per_1000"] - b["rate_per_1000"] for b in R["route"]]]
    ax.barh(lab, val, color=[ACCENT, MUTED], height=.5)
    ax.errorbar(val, lab, xerr=err, fmt="none", ecolor=INK, capsize=4, lw=1.2)
    for i, b in enumerate(R["route"]):
        ax.text(b["ci_hi_per_1000"] + max(val) * .03, i,
                "%d/%s" % (b["participants_affected"], f"{b['participants']:,}"),
                va="center", fontsize=9, color=INK)
    ax.set_xlabel("Tier-A (ventricular) events per 1,000 participants at risk\n"
                  "bars are 95% Wilson intervals", fontsize=9)
    ax.set_title("Route stratifies the ventricular endpoint", fontsize=11,
                 color=INK, loc="left")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(); fig.savefig(os.path.join(FIG, "route_rate.png"), dpi=200)
    plt.close(fig)

    top = pd.DataFrame(R["by_compound"]).head(10).iloc[::-1]
    fig, ax = plt.subplots(figsize=(7.6, 4.2))
    cols = [ACCENT if c else MUTED for c in top.cns]
    ax.barh(top.oligo_name, top.rate_per_1000, color=cols, height=.6)
    ax.errorbar(top.rate_per_1000, top.oligo_name,
                xerr=[top.rate_per_1000 - top.lo, top.hi - top.rate_per_1000],
                fmt="none", ecolor=INK, capsize=3, lw=1)
    ax.set_xlabel("Tier-A events per 1,000 participants (95% Wilson)", fontsize=9)
    ax.set_title("Per-compound observed rate — blue = CNS-delivered",
                 fontsize=11, color=INK, loc="left")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(); fig.savefig(os.path.join(FIG, "by_compound.png"), dpi=200)
    plt.close(fig)

    mods = [m for m in R["models"] if m["auc"] is not None]
    fig, ax = plt.subplots(figsize=(7.6, 3.4))
    names = [m["name"] for m in mods][::-1]
    vals = [m["auc"] for m in mods][::-1]
    cols = [WARN if "LEAKAGE" in n else ACCENT for n in names]
    ax.barh(names, vals, color=cols, height=.55)
    ax.axvline(.5, color=MUTED, ls="--", lw=1)
    for i, v in enumerate(vals):
        ax.text(v + .01, i, "%.2f" % v, va="center", fontsize=9, color=INK)
    ax.set_xlim(0, 1); ax.set_xlabel("Leave-one-compound-out AUC, tier-B outcome",
                                     fontsize=9)
    ax.set_title("Orange bars are provenance leakage probes, not models",
                 fontsize=11, color=INK, loc="left")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(); fig.savefig(os.path.join(FIG, "model_auc.png"), dpi=200)
    plt.close(fig)

    with open(os.path.join(HERE, "results.json"), "w") as fh:
        json.dump(R, fh, indent=1, default=str)

    write_report(R)

    print("arms %(n_arms)d | trials %(n_trials)d | compounds %(n_compounds)d | "
          "participants %(n_participants)d" % R)
    print("tier-A arms %(n_armsA)d | tier-B arms %(n_armsB)d" % R)
    for b in R["route"]:
        print("  %-38s %d/%d = %.2f per 1,000 (%.2f-%.2f)"
              % (b["label"], b["participants_affected"], b["participants"],
                 b["rate_per_1000"], b["ci_lo_per_1000"], b["ci_hi_per_1000"]))
    print("  Fisher OR %.2f, p = %.3g" % (R["route_fisher"]["odds_ratio"],
                                          R["route_fisher"]["p_value"]))
    print("  within-trial: treated %d/%d vs comparator %d/%d, OR %.2f p=%.3g"
          % (R["paired_treated_events"], R["paired_treated_n"],
             R["paired_ctrl_events"], R["paired_ctrl_n"],
             R["paired_fisher"]["odds_ratio"], R["paired_fisher"]["p_value"]))
    for m in R["models"]:
        print("  %-40s AUC %s (n=%d)" % (m["name"], m["auc"], m["n_scored"]))


if __name__ == "__main__":
    main()
