#!/usr/bin/env python3
"""
Predictive analysis of the hydrocephalus endpoint.

This script is deliberately conservative about what it claims. The endpoint is
rare: 9 of 526 trial arms report a tier-A (ventricular) event. Nine events will
not support a sequence-to-toxicity classifier, and presenting one would be
misleading. What the data does support is:

  1. Risk stratification by DELIVERY ROUTE, with exact confidence intervals and
     an exact test, at both arm and participant level.
  2. A modellable secondary outcome — tier B, CSF-dynamics disturbance — which
     occurs in 78 arms and is the mechanistic precursor the index case
     documents.
  3. A LEAKAGE TEST that quantifies how much of any apparent performance comes
     from provenance rather than biology. This is run because a review of the
     sibling kidney dataset found study_type and source_id were strong shortcut
     predictors of its label, and the same hazard applies here.

Validation is leave-one-COMPOUND-out, not random k-fold: arms of the same
compound are correlated, so a random split leaks the compound across folds and
inflates the score.

Outputs: ml/ML_REPORT.md, ml/results.json, ml/figures/*.png
Usage:   python3 ml/analyse.py   (after ml/build_analysis_set.py)
"""
import json
import os
import warnings

import numpy as np
import pandas as pd
from scipy import stats
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

warnings.filterwarnings("ignore")
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
FIG = os.path.join(HERE, "figures")
os.makedirs(FIG, exist_ok=True)

INK, MUTED, ACCENT, WARN = "#1F2933", "#7B8794", "#2C6E9B", "#B4551F"


def wilson(k, n):
    if n == 0:
        return (0.0, 0.0)
    lo, hi = stats.binomtest(k, n).proportion_ci(confidence_level=0.95,
                                                 method="wilson")
    return lo, hi



def write_report(R):
    """Render ml/ML_REPORT.md from the results just computed.

    This function is the correction to a real defect: the module docstring has
    always listed ML_REPORT.md as an output and the report itself opened with
    "Every number here is read from ml/results.json; none is typed" -- but
    nothing wrote it. It was typed by hand, and adding four trials to the
    registry left it asserting 526 arms and 155 trials against a results.json
    that said 546 and 159. A document that claims to be generated must be
    generated.
    """
    st = {}
    sp = os.path.join(os.path.dirname(HERE), "qc", "stats.json")
    if os.path.exists(sp):
        st = json.load(open(sp))
    cns = next(b for b in R["route"] if b["label"].startswith("CNS"))
    sysd = next(b for b in R["route"] if not b["label"].startswith("CNS"))
    by_name = {m["name"]: m for m in R["models"]}

    def _diag(which):
        for m in R["models"]:
            if "LEAKAGE" in m["name"] and which in m["name"]:
                return m.get("diagnostic", {"folds": 0, "constant_folds": 0})
        return {"folds": 0, "constant_folds": 0}

    def _fam(name):
        for m in R.get("models_sequence_family", []):
            if m["name"] == name and m["auc"] is not None:
                return "%.3f" % m["auc"]
        return "n/a"

    def _all(name):
        for m in R.get("models_all_axes", []):
            if m["name"] == name and m["auc"] is not None:
                return "%.3f" % m["auc"]
        return "n/a"

    def auc(name):
        m = by_name.get(name)
        return "%.3f" % m["auc"] if m and m["auc"] is not None else "n/a"

    n_seq = st.get("oligos_with_sequence", 0)
    n_olg = st.get("n_oligos", 0)
    n_vitro = st.get("n_in_vitro_rows", 0)
    vitro_clause = (
        "in vitro-to-in vivo extrapolation beyond the single compound that carries "
        "both (%d in vitro rows in the release)" % n_vitro if n_vitro else
        "in vitro-to-in vivo extrapolation (no in vitro rows exist)")

    md = """# Predictive analysis \u2014 hydrocephalus endpoint

Generated by `ml/analyse.py` from `ml/analysis_set.csv`. Every number here is
read from `ml/results.json`; none is typed.

## The unit of analysis is the trial arm, not the measurement row

`data/measurements.csv` is not a modelling table. Rows within an arm are not
independent \u2014 one arm contributes a row per adverse-event term, and one patient's
episode contributes a row per measurement (that is what `event_cluster_id`
marks). Treating them as independent inflates n by an order of magnitude and
shrinks every interval.

The analysis set aggregates to **one row per (trial, arm)**, which is a binomial
observation with a real denominator: {n_arms:,} arms across {n_trials:,} trials and
{n_compounds} compounds, {n_participants:,} participants at risk. It keeps only
`clinical_trial` rows with a denominator, so every observation is the same kind
of thing.

| | |
|---|---:|
| Arms | {n_arms:,} |
| Trials | {n_trials:,} |
| Compounds | {n_compounds} |
| Participants at risk (arm-sum) | {n_participants:,} |
| Arms with a tier-A (ventricular) event | **{n_armsA}** |
| Arms with a tier-B event, procedure complications excluded (primary) | **{n_armsB}** |
| Arms with any tier-B event, all axes (previous definition) | {n_armsB_all} |

**{n_armsA} tier-A arms will not support a classifier**, and this report does not
present one. What the data supports is route stratification, a modellable
tier-B outcome, and a leakage diagnosis.

## 1. Route stratifies the endpoint \u2014 between cohorts

| Route | Participants | Affected | Rate / 1,000 | 95% Wilson |
|---|---:|---:|---:|---|
| {cns_label} | {cns_n:,} | {cns_aff} | **{cns_rate:.2f}** | {cns_lo:.2f}\u2013{cns_hi:.2f} |
| {sys_label} | {sys_n:,} | {sys_aff} | {sys_rate:.2f} | {sys_lo:.2f}\u2013{sys_hi:.2f} |

Fisher exact odds ratio **{or_route:.2f}**, p = {p_route:.3g}.

## 2. And the contrast vanishes inside randomised comparisons

Restricting to the {paired_trials} trials carrying their own concurrent
comparator arm:

| | Events | Participants |
|---|---:|---:|
| Treated arms | {t_ev} | {t_n:,} |
| Comparator arms | {c_ev} | {c_n:,} |

Odds ratio **{or_paired:.2f}**, p = {p_paired:.2g}.
**No detectable within-trial effect.**

The two results are not in conflict; they are measuring different things. \u00a71
compares different diseases, ages and monitoring intensities. \u00a72 compares
randomised groups. Reporting \u00a71 alone would be the easiest way to mislead with
this dataset, which is why both are in it.

## 3. Models, and what they actually learn

Outcome: a tier-B (CSF-dynamics) event in an arm **excluding
`delivery_procedure_complication`** \u2014 {n_armsB} of {n_arms:,} arms. A lumbar-puncture
complication is a procedure outcome, not a compound toxicity, and the dataset's
own documentation says that axis must be excluded from compound-toxicity
analysis. Oscar set this as the default outcome on 2026-10-03; \u00a73b shows exactly
what that decision changed. German retains scientific adjudication.

Validation is **leave-one-compound-out**: arms of one compound are correlated, so
a random split leaks the compound across folds and inflates the score.

| Model | LOCO AUC |
|---|---:|
| Route only | {auc_route} |
| **Route + indication** | **{auc_ri}** |
| Route + indication + chemistry | {auc_ric} |
| *Leakage probe: trial identity only* | *{auc_trial}* |
| *Leakage probe: compound identity only* | *{auc_cmpd}* |

Bootstrap 95% CI for the best model: **{ci_lo:.3f}\u2013{ci_hi:.3f}**.

Transparent reference, as \u00a7G requires: the majority class (no event) is
**{maj:.1%}** of {n_rows} arms, and the no-information AUC is **0.5**. Any model
at or below those is worthless. Length-only, chemistry-only and family-only
baselines are **not fitted** \u2014 at {n_pos} positives they would not be
interpretable, and fitting them is a modelling decision for German rather than a
gap this analysis closed. Fold degeneracy is now reported for every model, not
only for the leakage probes.

> **That interval contains 0.5, so the primary model is not distinguishable from
> chance.** This is the direct consequence of excluding procedure complications:
> the outcome drops to {n_armsB} positive arms, and at that count the data do not
> support a predictive model. The release should be argued on the descriptive
> route stratification in \u00a71\u2013\u00a72, not on a classifier.

Three things worth reading off that table:

- **Adding chemistry makes it worse.** Chemistry is `NOT_REPORTED` for most
  compounds, so the feature contributes noise. This is a data-coverage result,
  not a biological one.
- **Trial identity alone reaches {auc_trial}**, and unlike the compound probe it
  is less degenerate (constant in {trial_const} of {trial_folds} folds) but is now
  also below chance. At {n_armsB} positives spread over {trial_folds} compounds,
  most folds contain no positive at all, so this probe is dominated by the same
  pooled-constant artefact as the compound one and supports no inference either
  way. Under the previous all-axes outcome it reached 0.724 and did carry signal;
  that reading does not transfer. A material share of any apparent
  performance is provenance, not biology. We ran this because a review of our
  sibling kidney dataset found `study_type` and `source_id` were strong shortcut
  predictors of its label.
- **Compound identity alone scores {auc_cmpd}, and that number means nothing.**
  An earlier version of this report read the below-chance value as "the correct
  behaviour under leave-one-compound-out" that "confirms the validation is doing
  its job". That reasoning was wrong, and a wrong reason quoted as a validation
  check is worse than no check. The probe is DEGENERATE: the held-out compound's
  own indicator column never exists in training, so its test design matrix is
  all-zero and every prediction in the fold is sigmoid(intercept) \u2014 a constant.
  The diagnostic now reports this directly: predictions are constant in
  {cmpd_const} of {cmpd_folds} folds. Pooled AUC therefore ranks fold constants
  against each other, not cases against controls, and lands far below 0.5 because
  removing an event-rich compound lowers the training base rate for exactly the
  fold that holds the events. The no-information value for this probe is 0.5;
  {auc_cmpd} is an artefact of pooled scoring, not evidence of anything. It is
  retained only as a transparency diagnostic.

## 3a. Grouped splits: compound, and sequence family

SCIENTIFIC_RULES §G requires grouped splits by sequence family, not only by
compound. Leave-one-compound-out is not sufficient on its own here: two pairs
share a base sequence and differ only in conjugation
(eplontersen/inotersen, olezarsen/volanesorsen), so holding out one leaves its
twin in training. Grouping by exact base-sequence equality collapses
{n_cmpd_model} compounds into {n_seqfam} families.

| Model | Leave-one-compound-out | Leave-one-sequence-family-out |
|---|---:|---:|
| Route only | {auc_route} | {auc_route_fam} |
| Route + indication | {auc_ri} | {auc_ri_fam} |
| Route + indication + chemistry | {auc_ric} | {auc_ric_fam} |

**The two agree to within 0.001 for these three models, under this grouping.**
That is a narrow sensitivity result and nothing wider. It says that collapsing
the two known exact-sequence pairs does not move these particular scores; it does
**not** establish that sequence leakage is immaterial at this endpoint. Grouping
removes an optimistic bias in expectation, but it carries no guarantee that a
score can only fall — the realised AUC is a noisy estimate and a fold can move
either way.

Leakage checks still **not** performed, so the \u00a7G and \u00a7K-10 requirement is
incomplete: near-neighbour (needs a similarity threshold, a scientific
judgement), modified/unmodified counterpart, strand, paper or study, and
experimental series. The grouped runs also carry **no uncertainty interval**,
which \u00a7K-11 requires. This endpoint is **not model-ready**, and nothing here
should be read as validation.

**No model permission is on record for this endpoint.** \u00a7H's release-state table
names thrombocytopenia, the human platelet POC, immunotoxicity and matched-context
analyses; it names no hydrocephalus item either way. So the permission that \u00a7H
governs has not been granted here and has not been refused either — it has not been
asked. The numbers in this section exist because they were computed before that gap
was noticed, and they are kept rather than deleted because deleting them would hide
what was run. They are **descriptive, exploratory and not authorised**: the
sequence-join normalization, the fold degeneracy and the bootstrap interval are all
stated so the work can be audited, not so a score can be quoted. Nothing in this
section may be strengthened, extended or carried into a deliverable until German
rules on it. The request is in
`ROCKSTEADY_GERMAN_QUESTION_model_permission_2026-10-03.md`.

This grouping is a **validation-safety measure, not an identity claim.** It
merges no inventory record, changes no count, and asserts nothing about whether
two constructs are the same molecule — it says only that they must not sit on
opposite sides of a split. The identity question stays unadjudicated.

Still outstanding under §G: **near-neighbour** grouping needs a sequence-similarity
threshold, which is a scientific judgement and is not set here; leave-one-paper-out
has no natural unit for this endpoint, where 155 of 195 sources are trial registry
records rather than papers; and transparent baselines (null/majority, length-only,
chemistry-only, family-only) are not yet fitted.

## 3b. What excluding procedure complications changed

This is the most consequential decision in this report, so the discarded
definition is kept rather than dropped.

Under the previous definition \u2014 any tier-B event \u2014 the outcome occurred in
{n_armsB_all} of {n_arms:,} arms. But **{proc_only} of those {n_armsB_all} carried
`delivery_procedure_complication` as their ONLY positive axis**. The model was
therefore substantially predicting *was this arm lumbar-punctured*, from a route
feature \u2014 a tautology, since the route is how the procedure happens.

| Model | Primary: procedure complications EXCLUDED | Previous: all tier-B axes |
|---|---:|---:|
| Route only | **{auc_route}** | {auc_route_all} |
| **Route + indication** | **{auc_ri}** | {auc_ri_all} |
| Route + indication + chemistry | **{auc_ric}** | {auc_ric_all} |
| Positive arms | **{n_armsB}** | {n_armsB_all} |

The headline falls from {auc_ri_all} to **{auc_ri}**. That is the honest number:
the earlier figure was inflated by a procedure effect the dataset was never
meant to attribute to a compound. What survives rests on **{n_armsB} positive
arms**, which is thin, and no predictive claim in this release should be quoted
without that denominator attached.

## 4. What this supports, and what it does not

**Supported:** descriptive, route- and population-stratified risk *stratification*;
separating drug effect from procedure and disease effect \u2014 which is exactly what
the outcome change in \u00a73b does; modelling ascertainment explicitly as a covariate;
hypothesis generation for CSF-dynamics monitoring in intrathecal programmes.

**No longer claimed:** a predictive classifier. With procedure complications
excluded the best model's bootstrap interval includes 0.5. The earlier 0.910 was
largely a procedure effect, and reporting it as predictive performance would
overstate what this dataset can do.

**Not supported:** sequence-to-toxicity prediction across the roster
({n_seq} of {n_olg} compounds carry a sequence); within-compound dose\u2013response for
tier A; {vitro_clause}; any causal claim about an individual compound, given \u00a72;
and any predictive claim quoted without the {n_armsB}-positive-arm denominator
and the \u00a73b comparison.

## Reproducing

```bash
python3 ml/build_analysis_set.py
python3 ml/analyse.py
```
""".format(
        n_arms=R["n_arms"], n_trials=R["n_trials"], n_compounds=R["n_compounds"],
        n_participants=R["n_participants"], n_armsA=R["n_armsA"],
        n_armsB=R["n_armsB"],
        cns_label=cns["label"], cns_n=cns["participants"],
        cns_aff=cns["participants_affected"], cns_rate=cns["rate_per_1000"],
        cns_lo=cns["ci_lo_per_1000"], cns_hi=cns["ci_hi_per_1000"],
        sys_label=sysd["label"], sys_n=sysd["participants"],
        sys_aff=sysd["participants_affected"], sys_rate=sysd["rate_per_1000"],
        sys_lo=sysd["ci_lo_per_1000"], sys_hi=sysd["ci_hi_per_1000"],
        or_route=R["route_fisher"]["odds_ratio"],
        p_route=R["route_fisher"]["p_value"],
        paired_trials=R["paired_trials"], t_ev=R["paired_treated_events"],
        t_n=R["paired_treated_n"], c_ev=R["paired_ctrl_events"],
        c_n=R["paired_ctrl_n"], or_paired=R["paired_fisher"]["odds_ratio"],
        p_paired=R["paired_fisher"]["p_value"],
        auc_route=auc("route only"), auc_ri=auc("route + indication"),
        auc_ric=auc("route + indication + chemistry"),
        auc_trial=auc("LEAKAGE PROBE: trial identity only"),
        auc_cmpd=auc("LEAKAGE PROBE: compound identity only"),
        cmpd_const=_diag("compound")["constant_folds"],
        cmpd_folds=_diag("compound")["folds"],
        trial_const=_diag("trial")["constant_folds"],
        trial_folds=_diag("trial")["folds"],
        n_armsB_all=R["n_armsB_all_axes"],
        maj=R["baseline"]["majority_class_rate"],
        n_rows=R["baseline"]["n_rows"], n_pos=R["baseline"]["n_positive"],
        n_seqfam=R.get("n_sequence_families", 0),
        n_cmpd_model=R.get("n_compounds_in_model", 0),
        auc_route_fam=_fam("route only"), auc_ri_fam=_fam("route + indication"),
        auc_ric_fam=_fam("route + indication + chemistry"),
        proc_only=R["n_armsB_all_axes"] - R["n_armsB"],
        auc_route_all=_all("route only"), auc_ri_all=_all("route + indication"),
        auc_ric_all=_all("route + indication + chemistry"),
        ci_lo=R["best_model_auc_ci"][0], ci_hi=R["best_model_auc_ci"][1],
        n_seq=n_seq, n_olg=n_olg, vitro_clause=vitro_clause)

    with open(os.path.join(HERE, "ML_REPORT.md"), "w") as fh:
        fh.write(md)


def main():
    df = pd.read_csv(os.path.join(HERE, "analysis_set.csv"))
    R = {}

    R["n_arms"] = int(len(df))
    R["n_trials"] = int(df.nct_id.nunique())
    R["n_compounds"] = int(df.oligo_name.nunique())
    R["n_participants"] = int(df.n_at_risk.sum())
    R["n_armsA"] = int(df.tierA_event.sum())
    # OUTCOME DEFINITION, decided by Oscar on 2026-10-03 after this analysis
    # showed 66 of the 84 tier-B positive arms carried
    # delivery_procedure_complication as their ONLY positive axis. A lumbar-
    # puncture complication is a procedure outcome, not a compound toxicity, and
    # the dataset's own documentation says that axis must be excluded from
    # compound-toxicity analysis. The PRIMARY outcome is therefore tier-B with
    # that axis removed; the all-axes version is retained as a sensitivity
    # analysis so the difference stays visible rather than being quietly dropped.
    R["n_armsB_all_axes"] = int(df.tierB_event.sum())
    R["n_armsB"] = int(df.tierB_event_nonprocedure.sum())
    R["outcome_definition"] = (
        "tier-B (CSF-dynamics) event in an arm, EXCLUDING "
        "delivery_procedure_complication. Set as the default outcome by Oscar on "
        "2026-10-03; German retains scientific adjudication.")

    # ---- 1. route stratification, arm level and participant level ----------
    def block(sub, label):
        arms, ev = len(sub), int(sub.tierA_event.sum())
        pa, pn = int(sub.tierA_affected.sum()), int(sub.n_at_risk.sum())
        lo, hi = wilson(pa, pn)
        return dict(label=label, arms=arms, arms_with_event=ev,
                    participants=pn, participants_affected=pa,
                    rate_per_1000=1000.0 * pa / pn if pn else 0.0,
                    ci_lo_per_1000=1000 * lo, ci_hi_per_1000=1000 * hi)

    cns = df[df.route_is_cns == 1]
    sys_ = df[(df.route_is_cns == 0) & (df.delivery_route != "NOT_REPORTED")]
    R["route"] = [block(cns, "CNS-delivered (intrathecal / ICV)"),
                  block(sys_, "Systemically delivered")]

    tbl = [[int(cns.tierA_affected.sum()),
            int(cns.n_at_risk.sum() - cns.tierA_affected.sum())],
           [int(sys_.tierA_affected.sum()),
            int(sys_.n_at_risk.sum() - sys_.tierA_affected.sum())]]
    odds, p = stats.fisher_exact(tbl)
    R["route_fisher"] = dict(odds_ratio=float(odds), p_value=float(p),
                             table=tbl)

    # ---- 2. per-compound observed tier-A rates -----------------------------
    g = df.groupby("oligo_name").agg(
        arms=("tierA_event", "size"), arms_with_event=("tierA_event", "sum"),
        affected=("tierA_affected", "sum"), at_risk=("n_at_risk", "sum"),
        cns=("route_is_cns", "max")).reset_index()
    g["rate_per_1000"] = 1000 * g.affected / g.at_risk
    g[["lo", "hi"]] = g.apply(
        lambda r: pd.Series([1000 * x for x in wilson(int(r.affected), int(r.at_risk))]),
        axis=1)
    R["by_compound"] = g.sort_values("rate_per_1000", ascending=False).head(14).to_dict("records")

    # ---- 3. within-trial comparator contrast -------------------------------
    # The strongest design available: treated and placebo arms of the SAME trial.
    pairs = []
    for nct, sub in df.groupby("nct_id"):
        tre, com = sub[sub.is_comparator == 0], sub[sub.is_comparator == 1]
        if len(com) == 0 or len(tre) == 0:
            continue
        pairs.append(dict(nct=nct,
                          treated_aff=int(tre.tierA_affected.sum()),
                          treated_n=int(tre.n_at_risk.sum()),
                          ctrl_aff=int(com.tierA_affected.sum()),
                          ctrl_n=int(com.n_at_risk.sum()),
                          cns=int(sub.route_is_cns.max())))
    P = pd.DataFrame(pairs)
    R["paired_trials"] = int(len(P))
    R["paired_treated_events"] = int(P.treated_aff.sum())
    R["paired_ctrl_events"] = int(P.ctrl_aff.sum())
    R["paired_treated_n"] = int(P.treated_n.sum())
    R["paired_ctrl_n"] = int(P.ctrl_n.sum())
    mt = stats.fisher_exact([[P.treated_aff.sum(), P.treated_n.sum() - P.treated_aff.sum()],
                             [P.ctrl_aff.sum(), P.ctrl_n.sum() - P.ctrl_aff.sum()]])
    R["paired_fisher"] = dict(odds_ratio=float(mt[0]), p_value=float(mt[1]))

    # ---- 4. modellable outcome: tier B, with honest validation -------------
    def design(frame, cols):
        X = pd.get_dummies(frame[cols].astype(str), drop_first=False)
        return X.astype(float), list(X.columns)

    def loco(frame, y, cols, group="oligo_name"):
        """Leave-one-GROUP-out CV. Random folds would leak the group.

        `group` defaults to compound. SCIENTIFIC_RULES G additionally requires
        grouping by sequence family, so the same splitter is run over
        `sequence_family` and both are reported.
        """
        preds, truth = [], []
        for comp in frame[group].unique():
            te = frame[group] == comp
            tr = ~te
            if y[tr].nunique() < 2 or te.sum() == 0:
                continue
            Xtr, names = design(frame[tr], cols)
            Xte, _ = design(frame[te], cols)
            Xte = Xte.reindex(columns=names, fill_value=0.0)
            mdl = LogisticRegression(max_iter=2000, class_weight="balanced", C=1.0)
            mdl.fit(Xtr, y[tr])
            preds.extend(mdl.predict_proba(Xte)[:, 1])
            truth.extend(y[te].tolist())
        if len(set(truth)) < 2:
            return None, len(truth)
        return roc_auc_score(truth, preds), len(truth)

    def loco_degeneracy(frame, y, cols):
        """Is this probe DEGENERATE — i.e. constant within every fold?

        For a feature that identifies the held-out group itself, the test design
        matrix is all-zero (the group's own column never existed in training), so
        every prediction in the fold is sigmoid(intercept): a constant. Pooled AUC
        then compares fold constants to each other, not cases to controls, and
        lands far below 0.5 because removing an event-rich compound lowers the
        training base rate for exactly the fold that holds the events. That is an
        artefact of the scoring, NOT evidence that leakage protection works.
        """
        n_folds = const = 0
        for comp in frame.oligo_name.unique():
            te = frame.oligo_name == comp
            tr = ~te
            if y[tr].nunique() < 2 or te.sum() == 0:
                continue
            Xtr, names = design(frame[tr], cols)
            Xte, _ = design(frame[te], cols)
            Xte = Xte.reindex(columns=names, fill_value=0.0)
            mdl = LogisticRegression(max_iter=2000, class_weight="balanced", C=1.0)
            mdl.fit(Xtr, y[tr])
            p = mdl.predict_proba(Xte)[:, 1]
            n_folds += 1
            if len(set(p.round(10))) == 1:
                const += 1
        return dict(folds=n_folds, constant_folds=const,
                    degenerate=(n_folds > 0 and const == n_folds))

    yB = df.tierB_event_nonprocedure      # primary; see outcome_definition
    models = {
        "route only": ["delivery_route"],
        "route + indication": ["delivery_route", "indication"],
        "route + indication + chemistry": ["delivery_route", "indication",
                                           "oligo_class", "backbone_chemistry"],
        "LEAKAGE PROBE: trial identity only": ["nct_id"],
        "LEAKAGE PROBE: compound identity only": ["oligo_name"],
    }
    R["models"] = []
    for name, cols in models.items():
        auc, n = loco(df, yB, cols)
        entry = dict(name=name, features=cols,
                     auc=None if auc is None else round(float(auc), 3),
                     n_scored=n)
        # Run the degeneracy diagnostic on EVERY model, not only the probes.
        # SCIENTIFIC_RULES G says to report failed or degenerate folds rather
        # than replacing them; a real model can be fold-degenerate too, and
        # reporting it only for the probes hid that possibility.
        entry["diagnostic"] = loco_degeneracy(df, yB, cols)
        R["models"].append(entry)

    # ---- SENSITIVITY: the same models against an outcome with the procedure
    #      complications removed. 78.6% of the tier-B positive arms carry
    #      delivery_procedure_complication as their ONLY positive axis, so the
    #      headline model is largely predicting "was this arm lumbar-punctured"
    #      from its own route feature — tautology, not compound toxicity.
    # TRANSPARENT REFERENCE (SCIENTIFIC_RULES G: "complex models must beat
    # transparent baselines"). The majority-class rate and the no-information
    # AUC are arithmetic, not fitted models, so they are reported here rather
    # than trained. Length-only, chemistry-only and family-only baselines ARE
    # models and are not fitted: with 18 positives they would be uninterpretable,
    # and fitting them is a modelling decision for German.
    n_pos = int(yB.sum())
    R["baseline"] = dict(
        n_rows=int(len(yB)), n_positive=n_pos,
        majority_class_rate=round(1 - n_pos / len(yB), 4),
        no_information_auc=0.5,
        note=("Majority-class accuracy is the share of arms with NO event; any "
              "accuracy at or below it is worthless. The no-information AUC is "
              "0.5 by construction. Length-only, chemistry-only and family-only "
              "baselines are NOT fitted -- see SCIENTIFIC_RULES G; that is a "
              "modelling decision for German, not a gap this session closed."))

    # GROUPED SPLITS (SCIENTIFIC_RULES G). Leave-one-compound-out is not
    # sufficient on its own: two pairs share a base sequence and differ only in
    # conjugation, so holding out one leaves its twin in training. Grouping by
    # sequence family removes that optimistic bias IN EXPECTATION. It does NOT
    # guarantee a lower score: the realised AUC is a noisy estimate and removing
    # a twin from training can move a fold either way. An earlier version of this
    # comment claimed grouping "can only lower the score", which is false.
    # Reported beside LOCO rather than replacing it.
    R["n_sequence_families"] = int(df.sequence_family.nunique())
    R["n_compounds_in_model"] = int(df.oligo_name.nunique())
    R["models_sequence_family"] = []
    for name, cols in models.items():
        if "LEAKAGE" in name:
            continue
        auc, n = loco(df, yB, cols, group="sequence_family")
        R["models_sequence_family"].append(
            dict(name=name, features=cols,
                 auc=None if auc is None else round(float(auc), 3), n_scored=n))

    # SENSITIVITY: the discarded definition, kept so the effect of the decision
    # is auditable rather than asserted.
    yBn = df.tierB_event
    R["n_armsB_nonprocedure"] = R["n_armsB"]        # retained key, same meaning
    R["models_all_axes"] = []
    for name, cols in models.items():
        if "LEAKAGE" in name:
            continue
        auc, n = loco(df, yBn, cols)
        R["models_all_axes"].append(
            dict(name=name, features=cols,
                 auc=None if auc is None else round(float(auc), 3), n_scored=n))

    # bootstrap CI for the best legitimate model
    best = ["delivery_route", "indication"]
    aucs = []
    rng = np.random.default_rng(0)
    for _ in range(300):
        idx = rng.choice(len(df), len(df), replace=True)
        sub = df.iloc[idx].reset_index(drop=True)
        a, _n = loco(sub, sub.tierB_event_nonprocedure, best)
        if a is not None:
            aucs.append(a)
    if aucs:
        R["best_model_auc_ci"] = [round(float(np.percentile(aucs, 2.5)), 3),
                                  round(float(np.percentile(aucs, 97.5)), 3)]

    # ---- figures -----------------------------------------------------------
    fig, ax = plt.subplots(figsize=(7.2, 3.4))
    lab = [b["label"].replace(" (", "\n(") for b in R["route"]]
    val = [b["rate_per_1000"] for b in R["route"]]
    err = [[b["rate_per_1000"] - b["ci_lo_per_1000"] for b in R["route"]],
           [b["ci_hi_per_1000"] - b["rate_per_1000"] for b in R["route"]]]
    ax.barh(lab, val, color=[ACCENT, MUTED], height=.5)
    ax.errorbar(val, lab, xerr=err, fmt="none", ecolor=INK, capsize=4, lw=1.2)
    for i, b in enumerate(R["route"]):
        ax.text(b["ci_hi_per_1000"] + max(val) * .03, i,
                "%d/%s" % (b["participants_affected"], f"{b['participants']:,}"),
                va="center", fontsize=9, color=INK)
    ax.set_xlabel("Tier-A (ventricular) events per 1,000 participants at risk\n"
                  "bars are 95% Wilson intervals", fontsize=9)
    ax.set_title("Route stratifies the ventricular endpoint", fontsize=11,
                 color=INK, loc="left")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(); fig.savefig(os.path.join(FIG, "route_rate.png"), dpi=200)
    plt.close(fig)

    top = pd.DataFrame(R["by_compound"]).head(10).iloc[::-1]
    fig, ax = plt.subplots(figsize=(7.6, 4.2))
    cols = [ACCENT if c else MUTED for c in top.cns]
    ax.barh(top.oligo_name, top.rate_per_1000, color=cols, height=.6)
    ax.errorbar(top.rate_per_1000, top.oligo_name,
                xerr=[top.rate_per_1000 - top.lo, top.hi - top.rate_per_1000],
                fmt="none", ecolor=INK, capsize=3, lw=1)
    ax.set_xlabel("Tier-A events per 1,000 participants (95% Wilson)", fontsize=9)
    ax.set_title("Per-compound observed rate — blue = CNS-delivered",
                 fontsize=11, color=INK, loc="left")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(); fig.savefig(os.path.join(FIG, "by_compound.png"), dpi=200)
    plt.close(fig)

    mods = [m for m in R["models"] if m["auc"] is not None]
    fig, ax = plt.subplots(figsize=(7.6, 3.4))
    names = [m["name"] for m in mods][::-1]
    vals = [m["auc"] for m in mods][::-1]
    cols = [WARN if "LEAKAGE" in n else ACCENT for n in names]
    ax.barh(names, vals, color=cols, height=.55)
    ax.axvline(.5, color=MUTED, ls="--", lw=1)
    for i, v in enumerate(vals):
        ax.text(v + .01, i, "%.2f" % v, va="center", fontsize=9, color=INK)
    ax.set_xlim(0, 1); ax.set_xlabel("Leave-one-compound-out AUC, tier-B outcome",
                                     fontsize=9)
    ax.set_title("Orange bars are provenance leakage probes, not models",
                 fontsize=11, color=INK, loc="left")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(); fig.savefig(os.path.join(FIG, "model_auc.png"), dpi=200)
    plt.close(fig)

    with open(os.path.join(HERE, "results.json"), "w") as fh:
        json.dump(R, fh, indent=1, default=str)

    write_report(R)

    print("arms %(n_arms)d | trials %(n_trials)d | compounds %(n_compounds)d | "
          "participants %(n_participants)d" % R)
    print("tier-A arms %(n_armsA)d | tier-B arms (primary, procedure excluded) "
          "%(n_armsB)d | tier-B all axes %(n_armsB_all_axes)d" % R)
    for b in R["route"]:
        print("  %-38s %d/%d = %.2f per 1,000 (%.2f-%.2f)"
              % (b["label"], b["participants_affected"], b["participants"],
                 b["rate_per_1000"], b["ci_lo_per_1000"], b["ci_hi_per_1000"]))
    print("  Fisher OR %.2f, p = %.3g" % (R["route_fisher"]["odds_ratio"],
                                          R["route_fisher"]["p_value"]))
    print("  within-trial: treated %d/%d vs comparator %d/%d, OR %.2f p=%.3g"
          % (R["paired_treated_events"], R["paired_treated_n"],
             R["paired_ctrl_events"], R["paired_ctrl_n"],
             R["paired_fisher"]["odds_ratio"], R["paired_fisher"]["p_value"]))
    for m in R["models"]:
        print("  %-40s AUC %s (n=%d)" % (m["name"], m["auc"], m["n_scored"]))


if __name__ == "__main__":
    main()
