#!/usr/bin/env python3
"""Source-verified corrections applied to the CNS lane extraction JSONs.

Each correction below was confirmed by reading the cited document directly during
curation — not accepted on a verifier's report alone — and each records what was
checked. Corrections are written to the lane files under
`notes/cns/extractions/`, which are the source of truth; the CSVs are then
regenerated by `scripts/assemble_cns.py`.

Usage:  python scripts/corrections_cns.py [--dry-run]
"""
import glob
import json
import os
import re
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXTRACT_DIR = os.path.join(ROOT, "notes", "cns", "extractions")


def norm(s):
    return re.sub(r"\s+", " ", ("" if s is None else str(s)).strip())


# ---------------------------------------------------------------------------
# C1. A fabricated exposure figure, propagated across 17 rows.
#
# Rows citing the Qalsody EPAR (EMA/276404/2024) carried
# "median 119.4wk (range 4-212wk)" / "up to 212wk". Neither number occurs
# ANYWHERE in that 181-page document - verified by full-text extraction of the
# PDF archived at sources/cns/EMA_Qalsody_EPAR_276404_2024.pdf: zero hits for
# "119.4" and zero for "212".
#
# What the EPAR actually says (section 2.6.8.1):
#   Pool ABCL1 - 147 participants exposed to tofersen 100 mg:
#       "The median total duration of exposure to tofersen 100 mg for this pool
#        was 148.4 weeks."
#   Pool ABCL2 - any dose: median 131.7 weeks, minimum 4, maximum 316 weeks.
#   "a maximum treatment duration of 245 weeks" for 100 mg.
#
# Every affected row uses an n=147 denominator, i.e. Pool ABCL1, so the corrected
# value is the Pool ABCL1 figure. This is the most serious defect verification
# found: a number that looks authoritative, cites a real document, and is absent
# from it.
# ---------------------------------------------------------------------------
EPAR_BAD = re.compile(r"119\.4|212\s*(wk|weeks)")
EPAR_GOOD = "median 148.4wk (max 245wk)"
EPAR_NOTE = ("corrected: exposure_duration 'median 119.4wk (range 4-212wk)' does not "
             "appear anywhere in EMA/276404/2024 (full-text checked, 0 hits for both "
             "119.4 and 212); the EPAR sec 2.6.8.1 gives Pool ABCL1 (n=147, 100 mg) "
             "median total exposure 148.4 weeks and a maximum treatment duration of "
             "245 weeks")

# ---------------------------------------------------------------------------
# C2. Zero-count adverse events filed as increases.
#
# Two rows record "papilloedema 0_of_63" and "0_of_44" with
# effect_direction=increase and grade 2. The counts are right at the locus, but
# the columns as written teach a model that zero events is a grade-2 increase.
# ---------------------------------------------------------------------------
ZERO_NOTE = ("corrected: a zero event count is not an increase; direction set to "
             "no_change and grade to 0, the count at the cited locus is unchanged")

# ---------------------------------------------------------------------------
# C3. A CSF opening-pressure range that overstates nothing but understates the
# peak. The row recorded 18-28.5 cmH2O from Lovett et al. Table 1. The tabulated
# values are 38, 18/20->21, 25.5 and 28, so the true range is 18-38; 28.5 appears
# nowhere. The same paper's individual values are separately recorded in this
# dataset as 28.0, 38.0 and 25.5, which is what exposed the discrepancy.
# ---------------------------------------------------------------------------
ICP_NOTE = ("corrected: range 18-28.5 replaced with 18-38; 28.5 does not appear in "
            "the cited table, whose values are 38, 18/20->21, 25.5 and 28 - the "
            "same paper's individual values are recorded separately in this dataset "
            "and disagreed with the range")


def main():
    dry = "--dry-run" in sys.argv
    stats = Counter()

    for path in sorted(glob.glob(os.path.join(EXTRACT_DIR, "*.json"))):
        d = json.load(open(path, encoding="utf-8"))
        changed = False
        for m in d.get("measurements", []):
            ref = norm(m.get("source_ref"))
            dur = norm(m.get("exposure_duration"))

            # C1 -----------------------------------------------------------
            if EPAR_BAD.search(dur) and ("276404" in ref or "1783" in ref
                                         or "215887" in ref):
                m["exposure_duration"] = EPAR_GOOD
                m["notes"] = norm(m.get("notes")) + " ;; " + EPAR_NOTE
                stats["C1_epar_exposure"] += 1
                changed = True

            # C2 -----------------------------------------------------------
            if re.match(r"^0[_ ]of[_ ]", norm(m.get("readout_value"))) and \
                    norm(m.get("effect_direction")) == "increase":
                m["effect_direction"] = "no_change"
                if norm(m.get("neurotox_grade")) != "0":
                    m["neurotox_grade"] = 0
                m["notes"] = norm(m.get("notes")) + " ;; " + ZERO_NOTE
                stats["C2_zero_count_direction"] += 1
                changed = True

            # C4 -----------------------------------------------------------
            # Sheep rows were filed as species=NA with the species disclosed only
            # in system_model and a note. That is honest but undiscoverable: `NA`
            # means "not applicable" in this schema, so anyone filtering by species
            # silently loses them. `sheep` is now in the vocabulary.
            if norm(m.get("species")) == "NA" and \
                    re.search(r"sheep", norm(m.get("system_model")), re.I):
                m["species"] = "sheep"
                m["notes"] = norm(m.get("notes")) + \
                    (" ;; corrected: species NA -> sheep; the species was previously "
                     "recoverable only from system_model, so species-based filtering "
                     "dropped these rows")
                stats["C4_sheep_species"] += 1
                changed = True

            # C3 -----------------------------------------------------------
            if norm(m.get("readout_value")) == "18-28.5" and \
                    "cmH2O" in norm(m.get("readout_unit")):
                m["readout_value"] = "18-38"
                m["effect_vs_control"] = ("CSF opening pressure 18-38 cmH2O across "
                                          "the four documented cases")
                m["notes"] = norm(m.get("notes")) + " ;; " + ICP_NOTE
                stats["C3_icp_range"] += 1
                changed = True

        if changed and not dry:
            json.dump(d, open(path, "w", encoding="utf-8"), indent=1)

    for k in sorted(stats):
        print("%-28s %d rows" % (k, stats[k]))
    if not stats:
        print("no rows matched - corrections already applied?")
    if dry:
        print("(dry run - nothing written)")


if __name__ == "__main__":
    main()
