#!/usr/bin/env python3
"""
Exports the dataset as OligoTox-Hydrocephalus_Dataset.xlsx.

Sheet layout matches the sibling OligoTox-CNS release — README, Summary,
data_dictionary, oligos, measurements, modifications, sources — so the two
endpoints can be read, and pooled, by the same tooling.

One deliberate difference from the CNS workbook. That one puts live COUNTA and
COUNTIF formulas in its Summary sheet, and its own README has to warn that "a
tool that reads cached values WITHOUT calculating (e.g. pandas.read_excel) will
see those cells as empty". Here the Summary carries VALUES, computed by
qc/validate.py into qc/stats.json and copied in at export time. The figures are
still generated rather than typed, but they survive being read by a machine.

Output: OligoTox-Hydrocephalus_Dataset.xlsx (repo root of this endpoint)
Usage:  python3 scripts/export_xlsx.py   (after qc/validate.py)
"""
import csv
import json
import os
import sys

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from data_dictionary import DICTIONARY

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "OligoTox-Hydrocephalus_Dataset.xlsx")

HEAD_FILL = PatternFill("solid", fgColor="1F3864")
HEAD_FONT = Font(color="FFFFFF", bold=True)
TITLE_FONT = Font(size=14, bold=True)


def load(name):
    with open(os.path.join(DATA, name)) as fh:
        return list(csv.reader(fh))


def write_table(ws, rows, freeze="A2"):
    for r in rows:
        ws.append(r)
    for c in range(1, len(rows[0]) + 1):
        cell = ws.cell(row=1, column=c)
        cell.fill, cell.font = HEAD_FILL, HEAD_FONT
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        width = max(len(str(rows[0][c - 1])) + 2,
                    *(min(len(str(r[c - 1])), 60) + 2
                      for r in rows[1:201]) if len(rows) > 1 else [12])
        ws.column_dimensions[get_column_letter(c)].width = min(max(width, 10), 60)
    ws.freeze_panes = freeze
    ws.auto_filter.ref = ws.dimensions


def write_prose(ws, blocks):
    ws.column_dimensions["A"].width = 118
    for text, style in blocks:
        ws.append([text])
        cell = ws.cell(row=ws.max_row, column=1)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        if style == "title":
            cell.font = TITLE_FONT
        elif style == "head":
            cell.font = Font(bold=True)


def main():
    stats_path = os.path.join(ROOT, "qc", "stats.json")
    if not os.path.exists(stats_path):
        sys.exit("qc/stats.json not found — run python3 qc/validate.py first")
    st = json.load(open(stats_path))

    wb = Workbook()

    # ---- README ---------------------------------------------------------
    ws = wb.active
    ws.title = "README"
    write_prose(ws, [
        ("OligoTox-Hydrocephalus — hydrocephalus and CSF-dynamics toxicity of "
         "oligonucleotide therapeutics", "title"),
        ("Dataset release v0.1 · NIH/NCATS Oligonucleotide Toxicity (OligoTox) Open "
         "Data Challenge, Phase 2 (Data Generation)", None),
        ("", None),
        ("What this is", "head"),
        ("An open, provenance-resolved dataset pairing oligonucleotide design with "
         "measured hydrocephalus and CSF-dynamics outcomes. Every row records where "
         "its value came from, how its severity grade was decided, how the endpoint's "
         "presence or absence was established, and what the source itself concluded "
         "about causation.", None),
        ("", None),
        ("Sheets", "head"),
        ("Summary            headline counts, generated by the QC suite", None),
        ("data_dictionary    every column in every table, with its definition", None),
        ("oligos             one row per oligonucleotide — the predictor variables", None),
        ("measurements       one row per measured outcome — the response variables", None),
        ("measurements_human   GENERATED view: the human evidence only — the most "
         "important subset. Every row carries the compound's SEQUENCE and design "
         "alongside its toxicity grade, so nothing has to be joined back.", None),
        ("measurements_animal  GENERATED view: the animal evidence only, same "
         "enrichment", None),
        ("German's analysis    GENERATED view: one row per compound — the oligo, its "
         "sequence, the per-position modification maps for that sequence, and its "
         "toxicity", None),
        ("modifications      one row per NUCLEOTIDE POSITION — the per-position "
         "chemistry", None),
        ("sources            the provenance registry", None),
        ("", None),
        ("How the tables join", "head"),
        ("measurements.oligo_id -> oligos.oligo_id (many measurements per "
         "oligonucleotide)", None),
        ("modifications.oligo_id -> oligos.oligo_id (one row per position, 5' to 3')", None),
        ("measurements.source_id and modifications.source_id -> sources.source_id", None),
        ("", None),
        ("Missing values — read this before analysing", "head"),
        ("NOT_REPORTED     the source does not report this value. It has NOT been "
         "estimated, imputed or filled from background knowledge.", None),
        ("NOT_APPLICABLE   the field has no meaning for this row (e.g. a comparator "
         "arm for a single-arm case report).", None),
        ("An empty cell    the field does not apply to this table's row type.", None),
        ("", None),
        ("In particular, purity_pct is NOT_REPORTED for all but three oligonucleotides "
         "here. A full-text sweep of all 16 committed US labels finds no statement of "
         "drug-substance purity, purification method or identity-confirmation method "
         "in any of them; the only stated purity value in the release (HPLC-purified, "
         "90-97%) comes from a 2007 academic paper. That is a property of the "
         "published record, not an omission in the curation; the sibling OligoTox-CNS "
         "release reports the same for all 1,839 of its compounds.", None),
        ("", None),
        ("Human and animal evidence are separated, in one column", "head"),
        ("subject_class divides every row into human_in_vivo, human_in_vitro, "
         "human_population, animal_in_vivo, animal_in_vitro or not_applicable. It is "
         "derived from (species, study_type) and re-derived by the QC suite, which "
         "fails on any disagreement, so the division cannot drift. The "
         "measurements_human and measurements_animal sheets are filters on it. "
         "human_population marks a population incidence rate: human subjects, but no "
         "individual dosed and no per-subject observation, so it is not a trial and "
         "must not be pooled with one.", None),
        ("", None),
        ("This release is overwhelmingly human clinical evidence, with ten animal rows "
         "and only two in vitro rows — both animal, from the one study that measures "
         "the same oligonucleotide in vitro and in vivo. The Challenge brief singles "
         "out in vitro HUMAN systems, and extrapolation between in vitro human systems "
         "and animal data, as of particular interest. This release has neither a human "
         "in vitro arm nor a substantial animal one, so it cannot support that "
         "extrapolation; that is the clearest limitation of the release and is stated "
         "here rather than left to be discovered.", None),
        ("", None),
        ("Reading the per-position modification maps", "head"),
        ("On the German's analysis sheet the three map columns are strings aligned to "
         "the sequence, one character per nucleotide. Sugar: M = 2'-MOE, d = 2'-deoxy "
         "(DNA), L = LNA, o = 2'-OMe, P = morpholino. Linkage (to the NEXT residue): "
         "S = phosphorothioate, o = phosphodiester, . = 3' terminus. 5-methyl: m where "
         "the base carries a 5-methyl group. So tofersen's sugar map "
         "MMMMMddddddddddMMMMM is a 5-10-5 gapmer read directly off the molecule. "
         "A '?' at a position means that dimension is NOT_REPORTED for that residue, and "
         "a column reading NOT_REPORTED means no per-position map could be established "
         "at all without guessing.", None),
        ("", None),
        ("Two tiers, never silently pooled", "head"),
        ("endpoint_tier A is the core endpoint: hydrocephalus, ventriculomegaly, "
         "ventricular volume, shunt or drain placement. Tier B is CSF-dynamics "
         "adjacent: raised intracranial pressure, papilloedema, aseptic or chemical "
         "meningitis, arachnoiditis, CSF leak or protein rise, post-lumbar-puncture "
         "syndrome. Any analysis that pools them must say so.", None),
        ("", None),
        ("Negatives are as load-bearing as positives", "head"),
        ("The ascertainment column separates measured_positive, measured_null "
         "(actively assessed and not found), reported_threshold_limited and "
         "not_assessed. A grade of 0 is permitted ONLY where ascertainment is "
         "measured_null — enforced by qc/validate.py, not merely documented. For this "
         "endpoint that distinction is decisive, because ventricular imaging is almost "
         "never protocol-specified.", None),
        ("", None),
        ("Three deliberate control classes", "head"),
        ("tox_axis = disease_background_rate marks rows with NO drug exposure — "
         "untreated-population incidence. tox_axis = "
         "delivery_procedure_complication marks events attributable to the lumbar "
         "puncture rather than to any molecule. tox_axis = "
         "therapeutic_ventricular_effect marks oligonucleotides whose measured "
         "ventricular effect is protective. All three must be excluded from a "
         "compound-toxicity analysis, and each is one filter away.", None),
        ("", None),
        ("Do not count event clusters twice", "head"),
        ("Rows sharing an event_cluster_id describe ONE clinical episode in the same "
         "subject(s). A single patient's hydrocephalus, CSF pressure, imaging and "
         "shunt are four measurements of one event, not four events.", None),
        ("", None),
        ("Grades are provisional", "head"),
        ("hydroceph_grade is an ordinal 0-3 severity assigned by the rule recorded in "
         "that row's grade_basis, per the rubric in SCHEMA.md. The scale is censored "
         "by study type — a CSF-composition row cannot reach grade 3, which is defined "
         "by whole-organism intervention — so grades are not comparable across "
         "study_type. All ship grade_status = provisional pending subject-matter-"
         "expert review.", None),
        ("", None),
        ("A note on the Summary sheet", "head"),
        ("The Summary sheet holds VALUES, not live formulas. They are computed by "
         "qc/validate.py into qc/stats.json and copied in at export time, so they are "
         "generated rather than typed but still survive being read by a tool that does "
         "not recalculate the workbook.", None),
        ("", None),
        ("How to cite", "head"),
        ("Cite this dataset AND the underlying primary sources listed on the 'sources' "
         "sheet. The great majority of rows are US Government works in the public "
         "domain (ClinicalTrials.gov, FAERS, DailyMed). The remainder are CC BY, "
         "CC BY-NC, summary-statistics-only where a licence carries a no-derivatives "
         "term, or 'verify' where reuse terms were not established. The redistribution "
         "column on each row records which terms apply to that row.", None),
    ])

    # ---- Summary --------------------------------------------------------
    ws = wb.create_sheet("Summary")
    write_prose(ws, [
        ("OligoTox-Hydrocephalus — Release v0.1. Every figure below is computed by "
         "qc/validate.py from the data sheets.", "title"),
        ("", None),
    ])
    ws.append(["Counts", ""])
    ws.cell(row=ws.max_row, column=1).font = Font(bold=True)
    for label, key in [("Oligonucleotides described", "n_oligos"),
                       ("— carrying at least one measurement", "n_oligos_with_measurements"),
                       ("Measurement rows", "n_measurements"),
                       ("Per-position modification records", "n_modification_positions"),
                       ("— over this many oligonucleotides", "n_oligos_with_position_map"),
                       ("Distinct sources", "n_sources"),
                       ("QC checks run", "checks_run"),
                       ("QC checks failed", "checks_failed")]:
        ws.append([label, st.get(key)])
    ws.append([])
    ws.append(["Coverage", ""])
    ws.cell(row=ws.max_row, column=1).font = Font(bold=True)
    for label, key in [("Oligonucleotides with a published sequence", "oligos_with_sequence"),
                       ("Oligonucleotides with a known length", "n_oligos_with_length"),
                       ("Tier-A rows with a positive finding", "tier_A_positive"),
                       ("Tier-A rows that are explicit measured negatives", "tier_A_null"),
                       ("Grade-3 (severe) rows", "grade3_rows")]:
        ws.append([label, st.get(key)])
    for title, key in [("Rows by subject class (human / animal division)", "by_subject_class"),
                       ("Rows by subject class and endpoint tier", "by_subject_class_and_tier"),
                       ("Rows by endpoint tier", "by_endpoint_tier"),
                       ("Rows by study type", "by_study_type"),
                       ("Rows by ascertainment", "by_ascertainment"),
                       ("Rows by attribution, as stated by the source", "by_attribution"),
                       ("Rows by toxicity axis", "by_tox_axis"),
                       ("Rows by severity grade", "by_grade"),
                       ("Rows by delivery route", "by_delivery_route"),
                       ("Rows by redistribution rights", "by_redistribution")]:
        ws.append([])
        ws.append([title, ""])
        ws.cell(row=ws.max_row, column=1).font = Font(bold=True)
        for k, v in (st.get(key) or {}).items():
            ws.append([k if k else "(not graded)", v])
    ws.column_dimensions["A"].width = 52
    ws.column_dimensions["B"].width = 14

    # ---- data_dictionary -------------------------------------------------
    ws = wb.create_sheet("data_dictionary")
    dd = [["table", "column", "definition"]]
    for tname in ("oligos", "measurements", "modifications", "sources"):
        header = load(tname + ".csv")[0]
        for col in header:
            dd.append([tname, col, DICTIONARY[tname][col]])
    write_table(ws, dd)
    ws.column_dimensions["C"].width = 100

    # ---- data sheets -----------------------------------------------------
    for name in ("oligos", "measurements", "modifications", "sources"):
        write_table(wb.create_sheet(name), load(name + ".csv"))

    # Human and animal evidence as separate sheets. These are GENERATED filters
    # on measurements.subject_class, not independent tables; the canonical
    # measurements sheet above contains every row exactly once.
    for sheet, fname in (("measurements_human", "measurements_human.csv"),
                         ("measurements_animal", "measurements_animal.csv"),
                         ("German's analysis", "germans_analysis.csv")):
        write_table(wb.create_sheet(sheet), load(fname))

    wb.save(OUT)
    size = os.path.getsize(OUT)
    print("wrote %s (%.1f MB)" % (OUT, size / 1e6))
    print("sheets: " + ", ".join(wb.sheetnames))


if __name__ == "__main__":
    main()
