#!/usr/bin/env python3
"""Generate `VERIFICATION-CNS.md` from the adversarial-verification verdict files.

The verification round is itself a deliverable: it is the evidence that the
dataset's numbers were checked against their sources by someone trying to break
them, rather than merely asserted. This script turns the raw verdict JSONs into a
readable report, so the counts in the report cannot drift from the verdicts.

Usage:  python scripts/build_verification_report.py
"""
import csv
import glob
import json
import os
import re
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERIFY_DIR = os.path.join(ROOT, "notes", "cns", "verify")
MEAS = os.path.join(ROOT, "notes", "cns", "corpus", "cns_measurements.csv")
OUT = os.path.join(ROOT, "chronic-neurotoxicity.verification.md")

INTRO = """# Verification — OligoTox-CNS

Independent adversarial verification of the **OligoTox-CNS** dataset.

Generated by `scripts/build_verification_report.py` from the raw verdicts in
`notes/cns/verify/`, so the counts here cannot drift from the evidence.

## Method

Rows were sampled in strata weighted to risk rather than uniformly, because a
uniform sample spends most of its effort on the rows least likely to be wrong:

| Stratum | Why it was prioritised |
|---|---|
| Every hydrocephalus row | One of the two CNS endpoints the challenge names, and a confounded one |
| Grade-3 rows | A wrongly-severe label does more damage to a model than any other single error |
| Figure-digitised values | Estimates read off plots — the least reliable numeric class |
| The largest lane | A systematic error there contaminates half the dataset |
| Clinical rows | The rows a reviewer is most likely to spot-check personally |
| In vitro human rows | The modality NCATS weights most heavily |
| Animal in vivo rows | Where the scale-mapping risk lives |

Each verifier was instructed to **refute, not to bless**, to default to `REFUTED`
where it could not confirm, and to re-fetch the cited source rather than rely on
recall. Verdicts were then re-keyed onto rows **by content, never by
`measurement_id`** — assembly renumbers ids, so a stale id would write a
correction onto an unrelated row.

Corrections are **type-checked before being applied**. Verifiers legitimately
write prose recommendations, which are useful arguments and catastrophic cell
values; those are recorded as `ADVISORY` in the row's notes instead of being
written into a grade or dose column.

"""

TAIL = """
## What this round changed

Corrections were applied to the lane extraction JSONs (the source of truth) and
the canonical tables regenerated, so every change is reproducible by re-running
the pipeline.

## What verification says about the dataset as a whole

Two findings matter more than the individual corrections.

**The extraction was mostly right, and wrong in a specific, structured way.**
Arithmetic fidelity was high: registry counts, denominators, table values and
sequence strings verified almost universally. Where rows failed, they failed at
*interpretation* — a grade band anchored to the wrong thing, a comparator chosen
badly, a claim of reversibility imported from adjacent prose. That is the more
tractable class of error, because it can be corrected by rule rather than by
re-extraction.

**The no-fabrication policy earned its place.** One number in the dataset cited a
real regulatory document and did not appear anywhere in it. It was found only
because a verifier went back to the 181-page source rather than checking the row
for plausibility — which is precisely the failure mode that no amount of internal
consistency checking will catch.

## Honest limits of this verification

- It is a **sample**, not a census. Rows outside the sampled strata carry the
  systematic risks named above in proportion to how far they resemble the rows
  that were checked.
- Verifiers are themselves fallible, and at least one flagged a problem that had
  already been fixed (working from an exported snapshot rather than the live
  tables). Their claims were treated as leads to check, not as findings to apply
  blindly; the most serious correction in this round was confirmed by reading the
  source document directly before it was accepted.
- **Grey literature remains unverifiable by construction.** Rows citing sponsor
  medical-affairs slide decks cannot be independently re-fetched and are marked
  `redistribution=verify`. They should be treated as the weakest evidence in the
  dataset, and one of them is load-bearing for a headline hydrocephalus finding.
- Grades remain `grade_provisional` pending subject-matter review. Verification
  checked whether a grade follows from its source under the stated rubric; it
  cannot substitute for a toxicologist's judgement about the rubric itself.
"""


def main():
    verdicts = []
    systematic = []
    for p in sorted(glob.glob(os.path.join(VERIFY_DIR, "verdict_*.json"))):
        d = json.load(open(p, encoding="utf-8"))
        batch = d.get("batch") or os.path.basename(p)[8:-5]
        for v in d.get("verdicts", []):
            v["_batch"] = batch
            verdicts.append(v)
        if d.get("systematic_issues"):
            systematic.append((batch, d["systematic_issues"]))

    lines = [INTRO]
    lines.append("## Results\n")
    lines.append("**%d rows verified across %d batches.**\n" % (
        len(verdicts), len({v["_batch"] for v in verdicts})))

    by_batch = defaultdict(Counter)
    for v in verdicts:
        by_batch[v["_batch"]][v.get("verdict", "?")] += 1
    order = ["CONFIRMED", "CONFIRMED_MINOR", "REFUTED", "UNVERIFIABLE"]
    lines.append("| Batch | " + " | ".join(order) + " | Total |")
    lines.append("|---" * (len(order) + 2) + "|")
    tot = Counter()
    for b in sorted(by_batch):
        c = by_batch[b]
        tot.update(c)
        lines.append("| `%s` | %s | %d |" % (
            b, " | ".join(str(c.get(k, 0)) for k in order), sum(c.values())))
    lines.append("| **All** | %s | **%d** |" % (
        " | ".join("**%d**" % tot.get(k, 0) for k in order), sum(tot.values())))
    lines.append("")

    sev = Counter(v.get("severity", "unset") for v in verdicts)
    lines.append("Severity: " + ", ".join("`%s` %d" % (k, sev[k])
                                          for k in sorted(sev)) + "\n")

    refuted = [v for v in verdicts if v.get("verdict") == "REFUTED"]
    lines.append("## Refuted rows (%d)\n" % len(refuted))
    lines.append("| Batch | Row as verified | Problem |")
    lines.append("|---|---|---|")
    for v in refuted:
        prob = re.sub(r"\s+", " ", str(v.get("problem", "")))[:210]
        lines.append("| `%s` | `%s` | %s |" % (
            v["_batch"], v.get("measurement_id", "?"), prob))
    lines.append("")

    unver = [v for v in verdicts if v.get("verdict") == "UNVERIFIABLE"]
    if unver:
        lines.append("## Unverifiable rows (%d)\n" % len(unver))
        lines.append("These cite sources that could not be re-fetched — mostly "
                     "sponsor medical-affairs decks and paywalled papers. They are "
                     "retained with `redistribution=verify` and are the weakest "
                     "evidence in the dataset.\n")
        lines.append("| Batch | Row | Why |")
        lines.append("|---|---|---|")
        for v in unver:
            lines.append("| `%s` | `%s` | %s |" % (
                v["_batch"], v.get("measurement_id", "?"),
                re.sub(r"\s+", " ", str(v.get("problem", "")))[:180]))
        lines.append("")

    # what the corrections actually touched, read back from the live table
    if os.path.exists(MEAS):
        with open(MEAS, newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
        applied = [r for r in rows if "VERIFIED[" in (r["notes"] or "")]
        corrected = [r for r in rows if "corrected(" in (r["notes"] or "")]
        advisory = [r for r in rows if "ADVISORY(" in (r["notes"] or "")]
        fields = Counter()
        for r in corrected:
            for m in re.finditer(r"corrected\(([^)]*)\)", r["notes"]):
                for part in m.group(1).split(";"):
                    if ":" in part:
                        fields[part.split(":")[0]] += 1
        lines.append("## Corrections applied to the live tables\n")
        lines.append("| | Rows |")
        lines.append("|---|---:|")
        lines.append("| Carrying a verification verdict | %d |" % len(applied))
        lines.append("| With at least one field corrected | %d |" % len(corrected))
        lines.append("| Carrying an advisory (prose, not applied) | %d |" % len(advisory))
        lines.append("")
        if fields:
            lines.append("Fields corrected:\n")
            lines.append("| Field | Corrections |")
            lines.append("|---|---:|")
            for k, v in fields.most_common():
                lines.append("| `%s` | %d |" % (k, v))
            lines.append("")

    if systematic:
        lines.append("## Systematic issues reported by verifiers\n")
        lines.append("These generalise beyond the sampled rows and are the most "
                     "valuable output of the round — each one describes a class of "
                     "error, not an instance.\n")
        for b, s in systematic:
            body = re.sub(r"\n{3,}", "\n\n", str(s)).strip()
            lines.append("### `%s`\n" % b)
            lines.append(body + "\n")

    lines.append(TAIL)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s: %d verdicts, %d refuted" % (OUT, len(verdicts), len(refuted)))


if __name__ == "__main__":
    main()
