#!/usr/bin/env python3
"""Generate `sources/SOURCES-CNS.md`, the source registry for the CNS dataset.

The registry is generated from the data rather than maintained by hand, so it can
never claim a source the dataset does not actually cite, or miss one it does.
Re-run after any change to the canonical tables.

Usage:  python scripts/build_sources_cns.py
"""
import csv
import os
import re
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEAS = os.path.join(ROOT, "notes", "cns", "corpus", "cns_measurements.csv")
OUT = os.path.join(ROOT, "chronic-neurotoxicity.sources.md")
LOCAL = os.path.join(ROOT, "sources", "cns")

HEADER = """# Sources — OligoTox-CNS

**Generated by `scripts/build_sources_cns.py` from `data/cns_measurements.csv`.**
Do not edit by hand: a registry maintained separately from the data drifts from
it, and then it is worse than no registry at all.

Every measurement row carries a canonical `source_ref` (NCT number, US patent
number, DOI or PMID) plus a `source_table` giving the exact locus — table,
figure, label section, claim, or API path — so any value can be re-verified
against its source in one lookup. Where a lane cited a document in prose, the
citation as written is preserved in the row's `notes` as `source_ref_as_cited=…`.

## How to read the rights column

`redistribution` is **read from the licence statement inside the source document
archived under `sources/cns/`**, not assumed from the journal or publisher.

| Value | Meaning |
|---|---|
| `public_domain` | US patents, FDA and EMA documents, ClinicalTrials.gov. Values may be reproduced without restriction. |
| `cc_by` | The source article is Creative Commons Attribution licensed, which permits reproducing raw values with attribution. This is what allows whole per-oligo panels to be republished verbatim. |
| `summary_stat` | Facts quoted from a source whose licence does not permit bulk reproduction — including **CC-BY-NC** and **CC-BY-ND** articles, which are deliberately *not* upgraded, since republishing their tables inside a CC-BY dataset would conflict with the non-commercial and no-derivatives terms. |
| `verify` | Rights unresolved. Must be settled before public release. |

## Source classes, in the order they were pursued

1. **US regulatory documents** — FDA prescribing information via DailyMed, and
   FDA application records. Public domain.
2. **EMA documents** — EPAR assessment reports, SmPCs, CHMP/PRAC records and
   Direct Healthcare Professional Communications. These proved decisive for
   hydrocephalus, which is documented in EU material with no US equivalent.
3. **US granted patents** — public domain, and uniquely valuable because they pair
   a formal sequence listing with per-compound tolerability tables. Sequence plus
   graded outcome is the modelling payload this dataset exists to supply.
4. **ClinicalTrials.gov posted results** — public-domain US government data whose
   adverse-event module is already at this dataset's grain (per-arm counts with
   denominators).
5. **Open-access primary literature** (PMC), with rights read per article.
6. **Paywalled trial publications and case series** — used only where the number
   could actually be read; rows resting on an abstract say so in `source_table`.

Reviews were used to *find* primary sources and to cross-check them, not as the
cited source for a value.

"""

FOOTER = """
## Known gaps in the source base

- **No FDA multi-disciplinary review PDFs.** `accessdata.fda.gov` serves a
  bot-detection page to non-browser clients, so the pharmacology/toxicology
  reviews — the likeliest home for unpublished non-human-primate CNS findings —
  were not retrieved. This is the single highest-value acquisition target for the
  next round.
- **No preclinical hydrocephalus source exists.** No published animal study was
  found in which an oligonucleotide *caused* hydrocephalus, and the nusinersen
  nonclinical package appears never to have measured ventricular size — which is
  plausibly why the signal only surfaced after marketing.
- **No in vitro model of CSF dynamics** for oligonucleotide toxicity exists at all.
- **Human iPSC neural toxicity literature is close to absent.** Searching found
  almost no study whose *purpose* is oligonucleotide toxicity in human
  iPSC-derived neural cells; nearly every human in vitro row was mined from the
  tolerability or control arms of efficacy papers.
- **Several clinically important papers are paywalled**, including the most
  compound-diverse non-human-primate intrathecal neurotoxicity survey.

## Source concentration — a stated risk

A small number of documents contribute a large share of rows. That is a real
concentration risk: an error in one of them propagates widely. Those sources were
correspondingly prioritised in verification, and the concentration is recorded in
`METHODOLOGY-CNS.md` as a limitation rather than left for a reader to discover
from the table above.
"""


def kind(ref):
    if ref.startswith("NCT"):
        return "ClinicalTrials.gov"
    if re.match(r"^US\d", ref):
        return "US patent"
    if ref.startswith("doi:") or ref.startswith("PMID"):
        return "Journal article"
    if ref.startswith("FDA"):
        return "FDA document"
    if ref.startswith("EMA") or ref.startswith("EMEA"):
        return "EMA document"
    return "Other / grey literature"


def main():
    with open(MEAS, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    agg = defaultdict(lambda: {"n": 0, "rights": Counter(), "study": Counter()})
    for r in rows:
        a = agg[r["source_ref"]]
        a["n"] += 1
        a["rights"][r["redistribution"]] += 1
        a["study"][r["study_type"]] += 1

    lines = [HEADER]
    lines.append("## Source registry — %d documents, %d rows\n"
                 % (len(agg), len(rows)))
    by_kind = Counter(kind(k) for k in agg)
    lines.append("| Source class | Documents |")
    lines.append("|---|---:|")
    for k, v in by_kind.most_common():
        lines.append("| %s | %d |" % (k, v))
    lines.append("")
    lines.append("| Source | Kind | Rows | Rights | Study types |")
    lines.append("|---|---|---:|---|---|")
    for ref, a in sorted(agg.items(), key=lambda kv: (-kv[1]["n"], kv[0])):
        label = ref if len(ref) <= 56 else ref[:53] + "..."
        lines.append("| `%s` | %s | %d | `%s` | %s |" % (
            label, kind(ref), a["n"], "`, `".join(sorted(a["rights"])),
            ", ".join("%s %d" % (k, v) for k, v in a["study"].most_common())))
    lines.append("")

    if os.path.isdir(LOCAL):
        files = sorted(os.listdir(LOCAL))
        total = sum(os.path.getsize(os.path.join(LOCAL, f))
                    for f in files if os.path.isfile(os.path.join(LOCAL, f)))
        lines.append("## Archived source documents\n")
        lines.append("%d files under `sources/cns/` (%.0f MB), so every derivation "
                     "can be re-run without network access.\n"
                     % (len(files), total / 1e6))

    lines.append(FOOTER)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s: %d sources" % (OUT, len(agg)))


if __name__ == "__main__":
    main()
