#!/usr/bin/env python3
"""Source-verified corrections applied to the CNS lane extraction JSONs.

Each correction below was confirmed by reading the cited document directly during
curation — not accepted on a verifier's report alone — and each records what was
checked. Corrections are written to the lane files under
`notes/cns/extractions/`, which are the source of truth; the CSVs are then
regenerated by `scripts/assemble_cns.py`.

Usage:  python scripts/corrections_cns.py [--dry-run]
"""
import glob
import json
import os
import re
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXTRACT_DIR = os.path.join(ROOT, "notes", "cns", "extractions")


def norm(s):
    return re.sub(r"\s+", " ", ("" if s is None else str(s)).strip())


# ---------------------------------------------------------------------------
# C1. A fabricated exposure figure, propagated across 17 rows.
#
# Rows citing the Qalsody EPAR (EMA/276404/2024) carried
# "median 119.4wk (range 4-212wk)" / "up to 212wk". Neither number occurs
# ANYWHERE in that 181-page document - verified by full-text extraction of the
# PDF archived at sources/cns/EMA_Qalsody_EPAR_276404_2024.pdf: zero hits for
# "119.4" and zero for "212".
#
# What the EPAR actually says (section 2.6.8.1):
#   Pool ABCL1 - 147 participants exposed to tofersen 100 mg:
#       "The median total duration of exposure to tofersen 100 mg for this pool
#        was 148.4 weeks."
#   Pool ABCL2 - any dose: median 131.7 weeks, minimum 4, maximum 316 weeks.
#   "a maximum treatment duration of 245 weeks" for 100 mg.
#
# Every affected row uses an n=147 denominator, i.e. Pool ABCL1, so the corrected
# value is the Pool ABCL1 figure. This is the most serious defect verification
# found: a number that looks authoritative, cites a real document, and is absent
# from it.
# ---------------------------------------------------------------------------
EPAR_BAD = re.compile(r"119\.4|212\s*(wk|weeks)")
EPAR_GOOD = "median 148.4wk (max 245wk)"
EPAR_NOTE = ("corrected: exposure_duration 'median 119.4wk (range 4-212wk)' does not "
             "appear anywhere in EMA/276404/2024 (full-text checked, 0 hits for both "
             "119.4 and 212); the EPAR sec 2.6.8.1 gives Pool ABCL1 (n=147, 100 mg) "
             "median total exposure 148.4 weeks and a maximum treatment duration of "
             "245 weeks")

# ---------------------------------------------------------------------------
# C2. Zero-count adverse events filed as increases.
#
# Two rows record "papilloedema 0_of_63" and "0_of_44" with
# effect_direction=increase and grade 2. The counts are right at the locus, but
# the columns as written teach a model that zero events is a grade-2 increase.
# ---------------------------------------------------------------------------
ZERO_NOTE = ("corrected: a zero event count is not an increase; direction set to "
             "no_change and grade to 0, the count at the cited locus is unchanged")

# ---------------------------------------------------------------------------
# C3. A CSF opening-pressure range that overstates nothing but understates the
# peak. The row recorded 18-28.5 cmH2O from Lovett et al. Table 1. The tabulated
# values are 38, 18/20->21, 25.5 and 28, so the true range is 18-38; 28.5 appears
# nowhere. The same paper's individual values are separately recorded in this
# dataset as 28.0, 38.0 and 25.5, which is what exposed the discrepancy.
# ---------------------------------------------------------------------------
ICP_NOTE = ("corrected: range 18-28.5 replaced with 18-38; 28.5 does not appear in "
            "the cited table, whose values are 38, 18/20->21, 25.5 and 28 - the "
            "same paper's individual values are recorded separately in this dataset "
            "and disagreed with the range")


# ---------------------------------------------------------------------------
# C5. Reversibility claimed where recovery was never assessed.
#
# `reversibility` is not decoration in this dataset: the challenge names CHRONIC
# neurotoxicity as an endpoint, so this column helps decide whether a row
# represents the high-priority endpoint at all. A wrongly-asserted `reversible`
# materially softens a toxicity finding.
#
# Two classes were asserting recovery that their sources never measured.
#
# (a) The mouse ICV acute-tolerability panel (doi:10.1089/nat.2021.0071). Its
#     Methods read: "For 1 h following the single bolus injection of ASO, animals
#     were observed for behavioral side effects". The paper's recovery language
#     ("waned anywhere between 2 and 4 h post-dose ... from 24 h and out to 7 days
#     we almost never observed any acute behavior reappearing") is explicitly
#     fenced to a DIFFERENT cohort - "observations of an initial set of 9 ASOs",
#     and "also, for this initial set, mice were injected with doses ranging from
#     12.5 to 200 ug". The scored panel was watched for one hour and never
#     re-examined; its supplementary table has no recovery, mortality or
#     follow-up column at all. So the claim was imported from adjacent prose.
#
#     Exception, kept deliberately: a score of exactly 20.0 is that scale's top
#     anchor, defined as "severe signs in all categories, including convulsions
#     resulting in euthanasia". That is a property of the animals actually scored,
#     not prose about others, so those rows keep `irreversible`.
#
# (b) Adverse-event INCIDENCE loci - ClinicalTrials.gov adverseEventsModule
#     entries, FDA label adverse-reaction tables, EPAR TEAE tables. These report
#     counts and have no outcome field whatsoever; the registry schema does not
#     even carry one. "Did not lead to discontinuation" and "all events were mild
#     or moderate" had been promoted into `reversible`, and neither is
#     reversibility. Resolution narratives in these documents attach to individual
#     SERIOUS events, and those rows are left alone.
# ---------------------------------------------------------------------------
HAG_PANEL = "10.1089/nat.2021.0071"
HAG_NOTE = ("corrected: reversibility -> not_assessed. The scored panel was observed "
            "for 1 h after a single ICV bolus and never re-examined; the paper's "
            "recovery statement is fenced to a separate initial set of 9 ASOs, and "
            "the supplementary table has no recovery or follow-up column")

AE_INCIDENCE = re.compile(r"adverseEventsModule|adverse[- ]reaction|adverse event|"
                          r"TEAE|Table 3[67]|otherEvents|seriousEvents", re.I)
AE_NOTE = ("corrected: reversibility -> not_assessed. This is an adverse-event "
           "INCIDENCE locus, which reports counts and carries no outcome field; "
           "'did not lead to discontinuation' and 'mild or moderate' are not "
           "reversibility")

# C6. A grade-0 row has no finding to reverse, so asserting recovery is
# meaningless there and quietly implies a resolved toxicity that never existed.
G0_NOTE = ("corrected: reversibility -> not_assessed on a grade-0 row; there is no "
           "finding to reverse")


def main():
    dry = "--dry-run" in sys.argv
    stats = Counter()

    for path in sorted(glob.glob(os.path.join(EXTRACT_DIR, "*.json"))):
        d = json.load(open(path, encoding="utf-8"))
        changed = False

        # C8. Grade-0 rows resting on SILENCE rather than on a measurement.
        #
        # "The paper did not report toxicity" is not "the paper measured toxicity
        # and found none", and only the second is a legitimate negative control.
        # The tell is a Methods-section locus with readout value, direction and
        # comparator all TBD, and a grade of 0 asserted anyway. Such a row claims
        # an outcome no measurement supports, which is more damaging than a
        # missing row: a model trained on it learns a false negative.
        before = len(d.get("measurements", []))
        d["measurements"] = [
            m for m in d.get("measurements", [])
            if not (norm(m.get("neurotox_grade")) == "0"
                    and norm(m.get("readout_value")) == "TBD"
                    and norm(m.get("effect_direction")) == "TBD"
                    and re.search(r"method", norm(m.get("source_table")), re.I))]
        dropped = before - len(d["measurements"])
        if dropped:
            stats["C8_silence_grade0_dropped"] += dropped
            changed = True

        for m in d.get("measurements", []):
            ref = norm(m.get("source_ref"))
            dur = norm(m.get("exposure_duration"))

            # C1 -----------------------------------------------------------
            if EPAR_BAD.search(dur) and ("276404" in ref or "1783" in ref
                                         or "215887" in ref):
                m["exposure_duration"] = EPAR_GOOD
                m["notes"] = norm(m.get("notes")) + " ;; " + EPAR_NOTE
                stats["C1_epar_exposure"] += 1
                changed = True

            # C2 -----------------------------------------------------------
            if re.match(r"^0[_ ]of[_ ]", norm(m.get("readout_value"))) and \
                    norm(m.get("effect_direction")) == "increase":
                m["effect_direction"] = "no_change"
                if norm(m.get("neurotox_grade")) != "0":
                    m["neurotox_grade"] = 0
                m["notes"] = norm(m.get("notes")) + " ;; " + ZERO_NOTE
                stats["C2_zero_count_direction"] += 1
                changed = True

            # C4 -----------------------------------------------------------
            # Sheep rows were filed as species=NA with the species disclosed only
            # in system_model and a note. That is honest but undiscoverable: `NA`
            # means "not applicable" in this schema, so anyone filtering by species
            # silently loses them. `sheep` is now in the vocabulary.
            if norm(m.get("species")) == "NA" and \
                    re.search(r"sheep", norm(m.get("system_model")), re.I):
                m["species"] = "sheep"
                m["notes"] = norm(m.get("notes")) + \
                    (" ;; corrected: species NA -> sheep; the species was previously "
                     "recoverable only from system_model, so species-based filtering "
                     "dropped these rows")
                stats["C4_sheep_species"] += 1
                changed = True

            # C5a ----------------------------------------------------------
            if HAG_PANEL in ref and norm(m.get("study_type")) == "animal_invivo" \
                    and norm(m.get("reversibility")) in ("reversible", "irreversible") \
                    and norm(m.get("readout_value")) not in ("20", "20.0"):
                m["reversibility"] = "not_assessed"
                m["notes"] = norm(m.get("notes")) + " ;; " + HAG_NOTE
                stats["C5a_hagedorn_reversibility"] += 1
                changed = True

            # C5b ----------------------------------------------------------
            if norm(m.get("reversibility")) == "reversible" and \
                    AE_INCIDENCE.search(norm(m.get("source_table"))) and \
                    "serious" not in norm(m.get("readout_name")).lower():
                m["reversibility"] = "not_assessed"
                m["notes"] = norm(m.get("notes")) + " ;; " + AE_NOTE
                stats["C5b_ae_incidence_reversibility"] += 1
                changed = True

            # C6 -----------------------------------------------------------
            if norm(m.get("neurotox_grade")) == "0" and \
                    norm(m.get("reversibility")) in ("reversible", "irreversible",
                                                     "partially_reversible"):
                m["reversibility"] = "not_assessed"
                m["notes"] = norm(m.get("notes")) + " ;; " + G0_NOTE
                stats["C6_grade0_reversibility"] += 1
                changed = True

            # C7 -----------------------------------------------------------
            # A Direct Healthcare Professional Communication is written and issued
            # by the marketing-authorisation holder and distributed through the
            # regulator; it is a company communication, not a government work, so
            # `public_domain` over-claims a right we do not have. Over-claiming
            # redistribution is a legal problem rather than a cosmetic one, and the
            # dataset tracks rights precisely so that it can be relied on.
            if norm(m.get("redistribution")) == "public_domain" and \
                    re.search(r"DHPC|Direct Healthcare Professional|press release|"
                              r"slide deck", ref + norm(m.get("source_table")), re.I):
                m["redistribution"] = "verify"
                m["notes"] = norm(m.get("notes")) + \
                    (" ;; corrected: redistribution public_domain -> verify; a Direct "
                     "Healthcare Professional Communication is issued by the marketing "
                     "authorisation holder, not by the regulator, so it is not a "
                     "government work")
                stats["C7_dhpc_rights_overclaim"] += 1
                changed = True

            # C3 -----------------------------------------------------------
            if norm(m.get("readout_value")) == "18-28.5" and \
                    "cmH2O" in norm(m.get("readout_unit")):
                m["readout_value"] = "18-38"
                m["effect_vs_control"] = ("CSF opening pressure 18-38 cmH2O across "
                                          "the four documented cases")
                m["notes"] = norm(m.get("notes")) + " ;; " + ICP_NOTE
                stats["C3_icp_range"] += 1
                changed = True

        if changed and not dry:
            json.dump(d, open(path, "w", encoding="utf-8"), indent=1)

    for k in sorted(stats):
        print("%-28s %d rows" % (k, stats[k]))
    if not stats:
        print("no rows matched - corrections already applied?")
    if dry:
        print("(dry run - nothing written)")


if __name__ == "__main__":
    main()
